### ISSUE TITLE
Redesign docker environment

### ISSUE THREAD

**Issue by otarza** [freeCodeCamp/freeCodeCamp#16642]
#### Issue Description

[docker-compose.yml](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/docker-compose.yml) is outdated, leading to broken installation of the project.

As discussed with @systimotic in Gitter room, I'll build relevant development environment for the project. 

## Tasks to do:

- [x] Rename `docker-compose.yml` to `sample.docker-compose.yml` and add` docker-compose.yml` to `.gitignore` - this way developers will be able to copy sample file and create their own `docker-compose.yml` files, giving them flexibility to make changes as they need.

### Define docker-compose services:
- [x] database service - mongo
- [x] web server - node
- [x] mail system - mailhog 

### Installation process:
- [x] Follow the project installation steps and make sure it leads to working instance of the project inside Docker environment. 
- [x] Document everything under project's installation section.

**Comment by raisedadead** [comment]
Thanks for the interest, and great to see that you are working on it, but that said please see https://github.com/freeCodeCamp/freeCodeCamp/issues/16226#issuecomment-353078476 while you work on this, for some of the criteria that we would like to be followed.

Happy contributing!

**Comment by otarza** [comment]
Hi @raisedadead, 

Thanks for the info. 

I don't expect any code changes for this issue, here is what I will need to change:

1. Rename `docker-compose.yml` to `sample.docker-compose.yml`;
2. Add `docker-compose.yml` to `.gitignore`;
3. Add a small sub-section in [CONTRIBUTING.md](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md) describing docker installation steps. 

There is no need to publish images to the registry because I don't expect that we will need any custom built images, just having `sample.docker-compose.yml` in our repo should be enough.

**Comment by raisedadead** [comment]
Perfect. Thanks a lot for taking this up.

**Comment by Bouncey** [comment]
@otarza I have been working on this in a pet project, I will give you what I have so far if you wish to continue with it

### docker-compose.yml
```yml
version: "3"
services:

  fcc-server:
    container_name: fcc-server
    build:
      context: ./
      dockerfile: production.Dockerfile
    ports:
      - "3000:3000"
    environment:
      MONGODB: mongodb://mongo:27017/freecodecamp
    depends_on:
      - mongo-seed
    command: npm start

  mongo-seed:
    container_name: mongo-seed
    build:
      context: ./
      dockerfile: base.Dockerfile
    environment:
      MONGODB: mongodb://mongo:27017/freecodecamp
      PORT: 3456
    depends_on:
      - mongo
    ports:
      - '3456:3456'
    command: node seed

  mongo:
    image: mongo
    container_name: mongo
    command: mongo
```

### base.Dockerfile
```
FROM node

ADD package.json /tmp/package.json
ADD package-lock.json /tmp/package-lock.json
RUN cd /tmp && npm install
RUN mkdir -p /usr/fcc && cp -a /tmp/node_modules /usr/fcc/

WORKDIR /usr/fcc
COPY . /usr/fcc

EXPOSE 3000
```

### production.Dockerfile
```
FROM node

ADD package.json /tmp/package.json
ADD package-lock.json /tmp/package-lock.json
RUN cd /tmp && npm install
RUN mkdir -p /usr/fcc && cp -a /tmp/node_modules /usr/fcc/

WORKDIR /usr/fcc
COPY . /usr/fcc

ENV NODE_ENV=production
RUN npm run build

EXPOSE 3000
```

I can't remember if I got the whole thing working, but i definitely got the db seeding during `compose`

Use it or not, I don't mind. Just thought you might find it useful

**Comment by otarza** [comment]
Hi @Bouncey, 

Thank you very much, this might be really helpful.

**Comment by ojongerius** [comment]
How is this work going guys? This would be so much win in regards to getting people up to speed.

**Comment by raisedadead** [comment]
Hi @ojongerius we could use some help in QA of the linked PR.

**Comment by ojongerius** [comment]
@raisedadead cool, had a look 😄
