### ISSUE TITLE
All certificate project titles should link to the projects on Learn

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#17284]
![settings___freecodecamp](https://user-images.githubusercontent.com/985197/40741508-60c1818e-6411-11e8-98fe-42a2b02a5036.png)

The challenge links:

- [ ] Build A Tribute Page: https://learn.freecodecamp.org/responsive-web-design/applied-responsive-web-design-projects/build-a-tribute-page
- [ ] Build A Survey Form: https://learn.freecodecamp.org/responsive-web-design/applied-responsive-web-design-projects/build-a-survey-form
- [ ] Build A Product Landing Page: https://learn.freecodecamp.org/responsive-web-design/applied-responsive-web-design-projects/build-a-product-landing-page
- [ ] Build A Technical Documentation Page: https://learn.freecodecamp.org/responsive-web-design/applied-responsive-web-design-projects/build-a-technical-documentation-page
- [ ] Build A Personal Portfolio Webpage: https://learn.freecodecamp.org/responsive-web-design/applied-responsive-web-design-projects/build-a-personal-portfolio-webpage
- [ ] Build A Random Quote Machine: https://learn.freecodecamp.org/front-end-libraries/front-end-libraries-projects/build-a-random-quote-machine
- [ ] Build A Markdown Previewer: https://learn.freecodecamp.org/front-end-libraries/front-end-libraries-projects/build-a-markdown-previewer
- [ ] Build A Drum Machine: https://learn.freecodecamp.org/front-end-libraries/front-end-libraries-projects/build-a-drum-machine
- [ ] Build A Java Script Calculator: https://learn.freecodecamp.org/front-end-libraries/front-end-libraries-projects/build-a-javascript-calculator
- [ ] Build A Pomodoro Clock: https://learn.freecodecamp.org/front-end-libraries/front-end-libraries-projects/build-a-pomodoro-clock
- [ ] Visualize Data With A Bar Chart: https://learn.freecodecamp.org/data-visualization/data-visualization-projects/visualize-data-with-a-bar-chart
- [ ] Visualize Data With A Scatterplot Graph: https://learn.freecodecamp.org/data-visualization/data-visualization-projects/visualize-data-with-a-scatterplot-graph
- [ ] Visualize Data With A Heat Map: https://learn.freecodecamp.org/data-visualization/data-visualization-projects/visualize-data-with-a-heat-map
- [ ] Visualize Data With A Choropleth Map: https://learn.freecodecamp.org/data-visualization/data-visualization-projects/visualize-data-with-a-choropleth-map
- [ ] Visualize Data With A Treemap Diagram: https://learn.freecodecamp.org/data-visualization/data-visualization-projects/visualize-data-with-a-treemap-diagram
- [ ] Timestamp Microservice: https://learn.freecodecamp.org/apis-and-microservices/api-and-microservice-projects/timestamp-microservice
- [ ] Request Header Parser Microservice: https://learn.freecodecamp.org/apis-and-microservices/api-and-microservice-projects/request-header-parser-microservice
- [ ] URL Shortener Microservice: https://learn.freecodecamp.org/apis-and-microservices/api-and-microservice-projects/url-shortener-microservice
- [ ] Exercise Tracker: https://learn.freecodecamp.org/apis-and-microservices/api-and-microservice-projects/exercise-tracker
- [ ] File Metadata Microservice: https://learn.freecodecamp.org/apis-and-microservices/api-and-microservice-projects/file-metadata-microservice
- [ ] Metric Imperial Converter: https://learn.freecodecamp.org/information-security-and-quality-assurance/information-security-and-quality-assurance-projects/metric-imperial-converter
- [ ] Issue Tracker: https://learn.freecodecamp.org/information-security-and-quality-assurance/information-security-and-quality-assurance-projects/issue-tracker
- [ ] Personal Library: https://learn.freecodecamp.org/information-security-and-quality-assurance/information-security-and-quality-assurance-projects/personal-library
- [ ] Stock Price Checker: https://learn.freecodecamp.org/information-security-and-quality-assurance/information-security-and-quality-assurance-projects/stock-price-checker
- [ ] Anonymous Message Board: https://learn.freecodecamp.org/information-security-and-quality-assurance/information-security-and-quality-assurance-projects/anonymous-message-board
- [ ] Build A Personal Portfolio Webpage: https://learn.freecodecamp.org/responsive-web-design/applied-responsive-web-design-projects/build-a-personal-portfolio-webpage
- [ ] Build A Random Quote Machine: https://learn.freecodecamp.org/front-end-libraries/front-end-libraries-projects/build-a-random-quote-machine
- [ ] Build A Pomodoro Clock: https://learn.freecodecamp.org/front-end-libraries/front-end-libraries-projects/build-a-pomodoro-clock
- [ ] Build A Java Script Calculator: https://learn.freecodecamp.org/front-end-libraries/front-end-libraries-projects/build-a-javascript-calculator
- [ ] Show The Local Weather: https://learn.freecodecamp.org/coding-interview-questions-and-take-home-assignments/coding-interview-take-home-projects/show-the-local-weather
- [ ] Use The Twitch JSON API: https://learn.freecodecamp.org/coding-interview-questions-and-take-home-assignments/coding-interview-take-home-projects/use-the-twitch-json-api
- [ ] Build A Tribute Page: https://learn.freecodecamp.org/responsive-web-design/applied-responsive-web-design-projects/build-a-tribute-page
- [ ] Build A Wikipedia Viewer: https://learn.freecodecamp.org/coding-interview-questions-and-take-home-assignments/coding-interview-take-home-projects/build-a-wikipedia-viewer
- [ ] Build A Tic Tac Toe Game: https://learn.freecodecamp.org/coding-interview-questions-and-take-home-assignments/coding-interview-take-home-projects/build-a-tic-tac-toe-game
- [ ] Build A Simon Game: https://learn.freecodecamp.org/coding-interview-questions-and-take-home-assignments/coding-interview-take-home-projects/build-a-simon-game
- [ ] Timestamp Microservice: https://learn.freecodecamp.org/apis-and-microservices/api-and-microservice-projects/timestamp-microservice
- [ ] Request Header Parser Microservice: https://learn.freecodecamp.org/apis-and-microservices/api-and-microservice-projects/request-header-parser-microservice
- [ ] URL Shortener Microservice: https://learn.freecodecamp.org/apis-and-microservices/api-and-microservice-projects/url-shortener-microservice
- [ ] Build An Image Search Abstraction Layer: https://learn.freecodecamp.org/coding-interview-questions-and-take-home-assignments/coding-interview-take-home-projects/build-an-image-search-abstraction-layer
- [ ] File Metadata Microservice: https://learn.freecodecamp.org/apis-and-microservices/api-and-microservice-projects/file-metadata-microservice
- [ ] Build A Voting App: https://learn.freecodecamp.org/coding-interview-questions-and-take-home-assignments/coding-interview-take-home-projects/build-a-voting-app
- [ ] Build A Nightlife Coordination App: https://learn.freecodecamp.org/coding-interview-questions-and-take-home-assignments/coding-interview-take-home-projects/build-a-nightlife-coordination-app
- [ ] Chart The Stock Market: https://learn.freecodecamp.org/coding-interview-questions-and-take-home-assignments/coding-interview-take-home-projects/chart-the-stock-market
- [ ] Manage A Book Trading Club: https://learn.freecodecamp.org/coding-interview-questions-and-take-home-assignments/coding-interview-take-home-projects/manage-a-book-trading-club
- [ ] Build A Pinterest Clone: https://learn.freecodecamp.org/coding-interview-questions-and-take-home-assignments/coding-interview-take-home-projects/build-a-pinterest-clone
- [ ] Build A Markdown Previewer: https://learn.freecodecamp.org/front-end-libraries/front-end-libraries-projects/build-a-markdown-previewer
- [ ] Build A Camper Leaderboard: https://learn.freecodecamp.org/coding-interview-questions-and-take-home-assignments/coding-interview-take-home-projects/build-a-camper-leaderboard
- [ ] Build A Recipe Box: https://learn.freecodecamp.org/coding-interview-questions-and-take-home-assignments/coding-interview-take-home-projects/build-a-recipe-box
- [ ] Build The Game Of Life: https://learn.freecodecamp.org/coding-interview-questions-and-take-home-assignments/rosetta-code-problems/conways-game-of-life
- [ ] Build A Roguelike Dungeon Crawler Game: https://learn.freecodecamp.org/coding-interview-questions-and-take-home-assignments/coding-interview-take-home-projects/build-a-roguelike-dungeon-crawler-game
- [ ] Visualize Data With A Bar Chart: https://learn.freecodecamp.org/data-visualization/data-visualization-projects/visualize-data-with-a-bar-chart
- [ ] Visualize Data With A Scatterplot Graph: https://learn.freecodecamp.org/data-visualization/data-visualization-projects/visualize-data-with-a-scatterplot-graph
- [ ] Visualize Data With A Heat Map: https://learn.freecodecamp.org/data-visualization/data-visualization-projects/visualize-data-with-a-heat-map
- [ ] Show National Contiguity With A Force Directed Graph: https://learn.freecodecamp.org/coding-interview-questions-and-take-home-assignments/coding-interview-take-home-projects/show-national-contiguity-with-a-force-directed-graph
- [ ] Map Data Across The Globe: https://learn.freecodecamp.org/coding-interview-questions-and-take-home-assignments/coding-interview-take-home-projects/map-data-across-the-globe

**Comment by nathanhannig** [comment]
this may run into reconciliation conflicts with my PR at https://github.com/freeCodeCamp/freeCodeCamp/pull/17903

I see the following challenges with this currently.
These are React components that are not hardcoded. A mapping of the challenges and their respective links might need to be implemented.
Legacy challenges will need to refer to their respective Modern challenge link.
An existing mapping of Modern challenges and a separate mapping of Legacy challenges exist and can be used. But I would imagine alterations would still need to be made.

**Comment by QuincyLarson** [comment]
Note that as @nathanhannig pointed out, these are not hard-coded (they should be). We're going to have to tackle this once we update the way /settings is built.

**Comment by ahmadabdolsaheb** [comment]
This feature has been implemented. 

![Screen Shot 2019-03-29 at 5 03 06 PM](https://user-images.githubusercontent.com/4591597/55238080-ac17b780-5244-11e9-8f27-2cb28230c381.png)
