### ISSUE TITLE
Need to convert remaining Blockquote elements in curriculum files to triple backtick version

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#35991]
Now that we have successfully proven that we can use triple backticks to replace our current use of `blockquote` elements to make the code more readable for maintainers (see PR #35926), the rest of the curriculum files and update the [Formatting challenge text](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/style-guide-for-curriculum-challenges.md#formatting-challenge-text) section of the `Style Guide for Curriculum Challenges` doc.

### Sections Needing Conversion
- [x] **JavaScript Algorithms And Data Structures** - PR #35992 (only 18 challenge files were converted (PR #35926) in the `Basic Data Structures` section of the `Javascript Algorithms And Data Structures` certification) 
- [x] **Responsive Web Design** - PR #35993 - merged
- [x] **Front End Libraries** - PR #35994 - merged
- [x] **Data Visualization** - PR #35995 - merged
- [x] **Apis And Microservices** - PR #35996 - merged
- [x] **Information Security And Quality Assurance** - PR #35997 - merged
- [x] **Coding Interview Prep** - PR #35998 - merged

### Documentation Needing Update
- [x] **Style Guide for Curriculum Challenges** - PR #36069

### Conversion of open PRs
In addition to the files in the sections listed above, the following open PRs have `blockquote` elements that need to be converted also.  We can either convert these on a case-by-case basis with an extra commit to the PR before merging OR wait until all of them have been merged and we can create a single PR to convert them.
- [x] https://github.com/freeCodeCamp/freeCodeCamp/pull/35415 - this has already been merged and was converted in PR #35995
- [x] https://github.com/freeCodeCamp/freeCodeCamp/pull/35966 - has been converted pre-merge
- [x] https://github.com/freeCodeCamp/freeCodeCamp/pull/35968 - has been converted pre-merge
- [x] https://github.com/freeCodeCamp/freeCodeCamp/pull/35982 - has been converted pre-merge

**Comment by leodaher** [comment]
@RandellDawson Can I take this issue? I can submit a PR soon for the update of the Style Guide for Curriculum Challenges.

**Comment by RandellDawson** [comment]
@leodaher Sure, you can tackle that one.  Try to give as much details as possible and an example to make it clear.  Thanks.

**Comment by ojeytonwilliams** [comment]
Regarding the Style Guide, it needs to stress that you can't use `yml` as a language, due to how it's parsed.  `yaml` is fine, though.  I'll update #36042 if needed.

**Comment by RandellDawson** [comment]
Everything has been merged which was related to this issue, so I am closing it.
