### ISSUE TITLE
Light/Dark toggle button on the nav

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#36819]
- [ ] Implement the gatsby themes.
- [ ] Implement the theme functionality in the nav.
- [ ] Implement the theme functionality using SSR to avoid flashing from default theme.
- [ ] Remove the theme related code from the client including calls to the api (no need to work on removing api from server itself).
- [ ] Default to night.
- [ ] Store the key in cookie and clear when user signs out.

**Comment by ojeytonwilliams** [comment]
Is the plan to store user preferences via cookies/localStorage?  If so, I suspect that hydration's still going to result in flash of the other theme, since parsing the cookies is handled by js.

Not that I think this is a bad idea, just that that problem might remain.

**Comment by ahmadabdolsaheb** [comment]
I share your concern. there are some theme toggle implementations using localhost and gatsby that we could look into to arrive at a solution.

I'm just adding this for my reference: 
https://github.com/gatsbyjs/gatsby/issues/15386

**Comment by raisedadead** [comment]
I am almost certain that we may end up using Gatsby's theme feature. So, we essentially have the dedicated themes for light, dark, etc. solving a class of problems.

**Comment by ojeytonwilliams** [comment]
@ahmadabdolsaheb from what I'm seeing in that thread, they're talking about the development server.  If there are issues with hydration, presumably they won't be visible until it's run in production mode.

**Comment by ojeytonwilliams** [comment]
> Would Gatsby pre-compile (SSR) the different sets assets and have them good to go? But we would still have to add a transition effect of some sorts just to make sure we are not splashing content, and 'transitioning'.

I assume so, yeah.  I imagine SSR gets the default mode good to go, but we'd need to handle/hide the transition if a cookie says 'show another mode'.

What I'd recommend is this. Build the light/dark toggle and solve the splash problem if and when it re-occurs.  Gatsby's complicated and it's possible I'm completely wrong about the hydration.

**Comment by raisedadead** [comment]
You are correct, the hydration issue is on the production, I'll explain how it works (albeit oversimplified) just to refresh this and make sure we are on the same page:

On development:
- Gatsby continuously builds and uses a web server to serve the asset bundles. 
- There is no delay in the 'rendered webpage' that your browser sees on first load. **The development server did the 'rendering' for us in this development case.**
- The JS and other asset bundles built by Gatsby then take over for rendering 'navigations and interactions' within the application later. This happens after the fact.

On production:
- We use Gatsby to build the asset bundles and serve it ourselves from a static host.
- In this case, the browser gets the barebone webpage (aka non-hydrated page) and asset bundles. The rendering now happens client side on the browser. There is a slight delay in the render. Often this is where you would see the loader.
- This is hence limited to production and only on the first load. Once the JS application logic takes over, the in app interactions now become snappy.

We optimize the SSR config on Gatsby, which essentially tells Gatsby: During a build please pre-render (hydrate) the page with the correct assets (we are doing this by defaulting to night mode assets).  

But this means a settings on client localStorage or cookie will result in conflict because that change means our client react application now has to re-render based on the setting. If its same as default the user does not see a difference. If its opposite of the default then due to the re-render the user sees it as the splash effect.

Now, I think by using Gatsby themes, we would be able to scaffold both (light/dark) the set of assets and by storing on cookie instead of localStorage we will be able to send the correct version down to the client?

Correct me if I missed anything in this theory?

**Comment by ojeytonwilliams** [comment]
The only thing I'm unsure on is:

> by storing on cookie instead of localStorage we will be able to send the correct version down to the client?

If that's how it works, problem solved!

**Comment by raisedadead** [comment]
I am unsure of that as well. That is the assumption in this theory, let's do some research.

If not a viable option, then the fallback is to delay the 'on client' theme change with a nice transition.

**Comment by ahmadabdolsaheb** [comment]
https://www.gatsbyjs.org/packages/gatsby-plugin-dark-mode/

**Comment by raisedadead** [comment]
While this is cool, its a utility shortcut? Should we rather not consider consider moving to native themes support by Gatsby as well.

**Comment by ojeytonwilliams** [comment]
It looks interesting - if I understand correctly it attaches the theme setting code to the html that's initially served. So, no flashing.

Trouble is, don't we use `theme` as prop? This just sets a class on the body, which is only part of the dark/light implementation.

**Comment by ahmadabdolsaheb** [comment]
this sets the class on the body and takes care of the persistence using localstorage.
so if we have two sets of classes like the following, it should probably work.
```
body {
  --primary-background: black;
}
body.dark {
  --primary-background: white;
}
```

**Comment by raisedadead** [comment]
> this sets the class on the body and takes care of the persistence using localstorage.

That is fine and is something what we almost already do (minus localStorage, plus user store), but what we really need to investigate is being able to hook into the build time (SSR) logic and generate the hydrated output assets.

Then based on the cookie try and serve the correct asset on the first request.

**Comment by ahmadabdolsaheb** [comment]
I will just add this for my reference 
https://github.com/gaearon/overreacted.io/blob/1224fd17cb1fd0d80f123d450ac8eee54c759786/src/html.js#L21

**Comment by ojeytonwilliams** [comment]
> this sets the class on the body and takes care of the persistence using localstorage.
> so if we have two sets of classes like the following, it should probably work.
> 
> ```
> body {
>   --primary-background: white;
> }
> body.dark {
>   --primary-background: black;
> }
> ```

That should work for everything except the editor, which handles its own theming based on a prop passed to it.  However even that should also be fine since it's lazy loaded (so presumably isn't part of the initial HTML).

> Then based on the cookie try and serve the correct asset on the first request.

So, is the plan just to try Gatsby themes and then, if there's still a problem with hydration, we look into using/modifiying something like https://www.gatsbyjs.org/packages/gatsby-plugin-dark-mode/ ?

**Comment by raisedadead** [comment]
We could add the plugin right away anyway. This is supposed to help who have OS/System level dark/light mode setup.

The Gatsby theme migration + some SSR magic should hopefully in getting rid of the splash.

**Comment by moT01** [comment]
What about not storing anything in storage, and just use the state - load the default theme, and if a user wants the other theme, they just have to toggle it every session.

**Comment by RandellDawson** [comment]
@moT01 I don't particularly like the dark theme, so I would prefer not to have to change it each session.

**Comment by raisedadead** [comment]
We have decided that the theme will be per browser, similar to what most implementations have it.

**Comment by raisedadead** [comment]
Update: We are sticking to our current production like implementation and we default to light mode. We are revisiting this again after shipping.

**Comment by ahmadabdolsaheb** [comment]
It would be more straight forward to offer dark/light switch only for show it for logged in users, so we could keep track of the user preferences across devices and in the future across services.

we currently have the theme switch in the menu on the forum, I could move that to the navigation as well.

I am not sure if we are planning to offer themes on news at this point ?

**Comment by raisedadead** [comment]
I think tracking the theme and trying to sync it is a bad idea. Youtube, Twitter, etc. track it per browser in a cookie etc.

This is also the case for discourse:

![image](https://user-images.githubusercontent.com/1884376/75972018-a288dc00-5ef8-11ea-9fbe-ede1335d3dba.png)

You would be able to avoid the flash of the default/night theme, and not to mention if used correctly we would not need to ship the unessential css unless requested for.

**Comment by ahmadabdolsaheb** [comment]
> * [ ]  Store the key in cookie and clear when user signs out.

If  users switch from the default theme ( dark ) to (light) and sign out, wouldn't they have to re-switch to light every time they sign in?

**Comment by raisedadead** [comment]
and why is that a concern? Isn't sign in === state ?

**Comment by ahmadabdolsaheb** [comment]
> Isn't sign in === state ?

I am not sure what exactly that refers to.

**Comment by raisedadead** [comment]
It was a rhetorical question. Why does a user sign in on any platform? To save their settings, data, etc. so that it is available when they come back. Sign out typically means that the settings can be reset. I would recommed you use your best judgement in implementing this. There are no wrong answers.
