### ISSUE TITLE
Python Curriculum Release Checklist

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#38911]
This is a checklist to be followed when we ship Python challenges globally. 

**Please expand this list as needed**

@raisedadead: DevOps

- [x] Remove the `SHOW_HIDDEN` limitation on build agents and code.
- [x] Push deployment to production. 
- [ ] Drop the challenges Collection. 
- [x] Remove redirecting beta forum links to production forum.
- [x] Remove the banner on top of beta site.

@freeCodeCamp/dev-team: Crit Issues 

- [x] https://github.com/freeCodeCamp/freeCodeCamp/issues/38934
- [x] https://github.com/freeCodeCamp/freeCodeCamp/issues/39013
- [x] https://github.com/freeCodeCamp/freeCodeCamp/issues/39028
- [x] https://github.com/freeCodeCamp/freeCodeCamp/issues/39041
- [x] https://github.com/freeCodeCamp/freeCodeCamp/issues/38609#issuecomment-644589187

@freeCodeCamp/dev-team: Outstanding issues on the project board:
- [ ] https://github.com/orgs/freeCodeCamp/projects/5#column-2658364

**Comment by ahmadabdolsaheb** [comment]
I might be missing something, but there does not seem to be a straight forward way to access the python challenges. Since they are not listed in learn. and landing page links go to learn.

**Comment by raisedadead** [comment]
> I might be missing something, but there does not seem to be a straight forward way to access the python challenges. Since they are not listed in learn. and landing page links go to learn.

This is a checklist only issue. Please create fresh issues as you find them.
