### ISSUE TITLE
Secure Real Time Multiplayer Project Tests

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/freeCodeCamp#40877]
Currently, the [SRTM Project](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/09-information-security/information-security-projects/secure-real-time-multiplayer-game.md) has no tests for most of the user-stories.

Discussion can be had within this issue about adding/changing/removing current user-stories. A PR does not need to cover every user-story, but try not to open a PR, if one is already aimed at resolving a specific user-story.

This issue is open for contributions aimed at adding to the user-stories outlined:
- [ ] Multiple players can connect to a server and play.
- [ ] Each player has an avatar.
- [ ] Each player is represented by an object created by the Player class in Player.mjs.
- [ ] At a minimum, each player object should contain a unique id, a score, and x and y coordinates representing the player's current position.
- [ ] The game has at least one type of collectible item. Complete the Collectible class in Collectible.mjs to implement this.
- [ ] At a minimum, each collectible item object created by the Collectible class should contain a unique id, a value, and x and y coordinates representing the item's current position.
- [ ] Players can use the WASD and/or arrow keys to move their avatar. Complete the movePlayer method in Player.mjs to implement this.
- [ ] The movePlayer method should accept two arguments: a string of "up", "down", "left", or "right", and a number for the amount of pixels the player's position should change. movePlayer should adjust the x and y coordinates of the player object it's called from.
- [ ] The player's score should be used to calculate their rank among the other players. Complete the calculateRank method in the Player class to implement this.
- [ ] The calculateRank method should accept an array of objects representing all connected players and return the string Rank: currentRanking/totalPlayers. For example, in a game with two players, if Player A has a score of 3 and Player B has a score of 5, calculateRank for Player A should return Rank: 2/2.
- [ ] Players can collide with a collectible item. Complete the collision method in Player.mjs to implement this.
- [ ] The collision method should accept a collectible item's object as an argument. If the player's avatar intersects with the item, the collision method should return true.
- [ ] All players are kept in sync.
- [ ] Players can disconnect from the game at any time.
- [x] Prevent the client from trying to guess / sniff the MIME type.
- [x] Prevent cross-site scripting (XSS) attacks.
- [x] Nothing from the website is cached in the client.
- [x] The headers say that the site is powered by "PHP 7.4.3" even though it isn't (as a security measure).

The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by gikf** [comment]
Few of these are implemented as [tests](https://github.com/freeCodeCamp/boilerplate-project-secure-real-time-multiplayer-game/tree/master/tests) in the boilerplate code. Could that be used, similarly to other projects, with call to `/_api/get-tests`? Or do they need to be tested more directly from project page, when that's possible?

**Comment by ShaunSHamilton** [comment]
> Could that be used, similarly to other projects, with call to /_api/get-tests? Or do they need to be tested more directly from project page, when that's possible?

Typically, the `/get-tests` route offers the meta data associated with the state of the user-written tests (as you have mentioned). Unfortunately, this means Campers could just write `assert.equal(true, true);` for each test, and pass the user stories as well.

So, the tests need to be more direct, and specific for each user story. Essentially, `/get-tests` is only used in the user stories that are something like:
> x number of functional tests should pass
> There should be x number of assertions in the unit tests

Hope this clarifies

**Comment by gikf** [comment]
How does this look? Four tests which are called separately, but still need to rely on some initial boilerplate code. https://github.com/gikf/freeCodeCamp/commit/028cbeab2e7992026e4d8ed653c0a382965fa6ad

I agree it would be better to be able to test it completely from outside, limit ways somebody can fool tests and be able to call tests one-by-one. I don't know however if that's possible.

**Comment by gikf** [comment]
Method to prevent caching also was removed in `helmet 4.x`, but boilerplate uses `3.22.0` by default. I suppose as long as project isn't explicitly changed to use newer version it's okay.

**Comment by a2937** [comment]
I've noticed a complication. A lot of the tests involve directly checking the class objects. But as they live on the Replit server or elsewhere; it's going to be a little difficult. I've thought about using simply fetching the script and evaluating it. However, it does lend a gigantic vulnerability to FreeCodeCamp's curriculum if  proper precautions aren't taken. Perhaps a test frame could be used like the [other challenges](https://github.com/freeCodeCamp/freeCodeCamp/blob/4f4b92f29c5826932a394c1df012ae32e31b0dfb/client/src/client/frame-runner.ts#L34).

**Comment by naomi-lgbt** [comment]
Ideally we should be able to do something similar to some of the other backend projects, where we have an endpoint in the boilerplate that our tests can call, and the boilerplate handles parsing the class objects and returning values for the tests to look at.

**Comment by a2937** [comment]
That seems reasonable. But for 

> Ideally we should be able to do something similar to some of the other backend projects, where we have an endpoint in the boilerplate that our tests can call, and the boilerplate handles parsing the class objects and returning values for the tests to look at.

That seems reasonable. But for campers that don't know Repl.it, they would have no clue how to set the NODE_ENV to test so the tests are actually broadcast back to the challenge.

**Comment by a2937** [comment]
How do we guarantee that it won't cause headaches down the line?

**Comment by naomi-lgbt** [comment]
> But for campers that don't know Repl.it, they would have no clue how to set the NODE_ENV to test so the tests are actually broadcast back to the challenge.

This isn't a challenge where they need to write tests and have the results exposed through the boilerplate's API. Ultimately, the boilerplate should only need to import and read the `Collision` and `Player` classes to be able to test the user stories.

**Comment by a2937** [comment]
Yes. This isn't a challenge where they need to write tests. I think I get what you're saying, at least somewhat. Hmm... I suppose we could add a route for the Player,Collision, and Collectible classes.

**Comment by anishlukk123** [comment]
@scissorsneedfoodtoo  is there any update on this ticket

**Comment by Sembauke** [comment]
Please re-open if you feel like this is worth keeping, as it is now part of the legacy curriculum
