### ISSUE TITLE
SolutionForm Link Validators Discussion

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/freeCodeCamp#41159]
This issue is to specifically discuss further implementation of: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/components/formHelpers/FormValidators.js

The current validators check for:
- [x] Repl editor links (e.g. `https://repl.it/@Sky020/some-project`)
- [x] Glitch editor links (e.g. `https://glitch.com/edit/#!/some-project`)
- [x] Codesandbox editor links (e.g. `https://codesandbox.io/s/sky020/some-project`)
- [x] General GitHub links (e.g. `https://github.com/freeCodeCamp/freeCodeCamp/`)
- [x] Localhost links (e.g. `http://localhost:3000`)
- [x] `Repl.it` 'join' links (resolved with #41094 ) (e.g. `https://repl.it/join/Sky020`)
- [x] `fCC` related links (`codepen.io/freecodecamp`, `freecodecamp.rocks`, `github.com/freecodecamp`) (resolved with #41094 )
- [x] unsecure `http` links which cannot be used by the tests (resolved with #41329 )

And **does not** check for:
- [ ] IPv4 and IPv6 addresses (e.g. `192.168.1.1:3000` or, more common, `http://127.0.0.1:5500`)

Any other thoughts? Should some/all of this be implemented?

**Comment by JoshuaPelealu** [comment]
>     * [ ]  Glitch 'join' links
It seems like that the Glitch 'join' links are discontinued but there is still a way around it (The way around would take you to open a terminal and echo the project token) So I don't think we have to worry too much on this link anymore AFAIK...

**Comment by JoshuaPelealu** [comment]
Another thing that's related, and needs to be fixed ASAP is that the fact that when you give the example projects for the Web Design Projects, it will accept it. This is not good. I was going to open a new issue, but it seems like it's related to this issue so I just put it here. 

Anyways, here's a GIF of a project able to pass using the example project link.
![Project-Passes](https://user-images.githubusercontent.com/45566099/108369240-5e562080-71c9-11eb-8add-eed5c376bdef.gif)

One way we can fix this is put all of the boilerplate and example code links into a JSON file or something a like, and then render it to the challenges and be able to use the file to check if the link given is a boilerplate code or an example link.

**Comment by ShaunSHamilton** [comment]
@JoshuaPelealu Thanks for that. This has always been the case. This is what I meant with:
>Prevent Campers from submitting the CodePen boilerplate, and not saving their project code

>Store project links within one config file

The main issue is Campers are editing the boilerplate link with their own code, and submitting it - forgetting to fork the project. Later, they try to view their project, but the code is gone, because they do not have write rights to the boilerplate.

**Comment by nhcarrigan** [comment]
Rather than looking for specific project links from CodePen, wasn't there discussion somewhere about a blanket disallow on `codepen.io/freecodecamp`? Then we wouldn't have to maintain a config of example projects.

**Comment by ShaunSHamilton** [comment]
> wasn't there discussion somewhere about a blanket disallow on codepen.io/freecodecamp?

@nhcarrigan Yes. This is one way to solve a problem. This would be quicker/easier.

However, I thought it could be easier/nicer to have one central file with all of the miscellaneous (spelt that right first time 😁 ) links to examples/boilerplates, which would be dynamically set into the pages.

**Comment by nhcarrigan** [comment]
Definitely - that would help with maintaining the links in general (single source of truth for the win). I think I'd still like to blanket-catch the freecodecamp account in the solution validation, though. What if we update a link and a camper finds + submits the old one?

**Comment by ShaunSHamilton** [comment]
> What if we update a link and a camper finds + submits the old one?

Ah, decent point. Then, I will add this to the current PR, and we can continue discussing centralising links.

**Comment by JoshuaPelealu** [comment]
So how are we approaching this problem?

**Comment by ShaunSHamilton** [comment]
@JoshuaPelealu I suspect some more discussion needs to be had about whether or not it is in our best interest to create a config of current links.

Ideally, we need to discuss implementation, as this would need to integrate with the Gatsby setup.

**Comment by nhcarrigan** [comment]
I'm wondering if that discussion should be a separate issue (since it no longer relates directly to the solution form).

**Comment by ShaunSHamilton** [comment]
@nhcarrigan Decent idea. I will open an issue for that specifically.

Then to close/not-close this issue, where do you stand on checking for `IPv4/v6` urls/addresses?

**Comment by moT01** [comment]
This seems pretty related https://github.com/freeCodeCamp/freeCodeCamp/pull/41162#issuecomment-784330415. Want to add it to the list @ShaunSHamilton? Or let me know if it feels like a separate issue and I'll make another one.

I suppose the test would be to require `https` submissions.

**Comment by RandellDawson** [comment]
What if someone wants to use `http://localhost` to work through the challenges?

**Comment by ShaunSHamilton** [comment]
I have a PR open now, that touches this side of the client. So, I will dig into adding this, and see about what @RandellDawson has mentioned about going through the non-projects with `localhost` links.

I will probably make some logic to differentiate what happens to the submission validation, based on the challenge being project or not.

**Comment by RandellDawson** [comment]
@ShaunSHamilton Can this be closed or are further PRs needed?

**Comment by ShaunSHamilton** [comment]
@RandellDawson It is still up for discussion whether or not we want to go the route of adding:
> IPv4 and IPv6 addresses (e.g. 192.168.1.1:3000 or, more common, http://127.0.0.1:5500)

---

_Originally posted by Nicholas (above)_
> Wouldn't hurt - I think I've only seen someone submit that once (based on forum posts), but extra sanity checks are always nice to have IMHO.
> 
> But it's also not a blocking issue, so I wouldn't prioritise it.

**Comment by RandellDawson** [comment]
@ShaunSHamilton Maybe if a user submits an ip address, we give them a message to use `localhost` instead?  I am not sure this is the best way or if we want to get into messaging like this, but off the top of my head, that is the first thing I think.
