### ISSUE TITLE
chore: Replace single line inline code blocks with multi-line code blocks

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#41518]
To make single line code code blocks stand out more, we want to replace all such inline code blocks with multi-line code blocks in the Description and Instructions sections of a challenge.  There were 4 files that also had extra characters at the end, that have already been fixed (see PR #41498), so If you search all the files located in `curriculum/challenges/english` with the following regex, you will find all the instances remaining to be fixed. 

**NOTE:**  Do not include the Python challenges. The single line code blocks are in the Answers section which we do not want to change at this point.
```js
/^`[^`]+?`$/gi
```
Each replacement should make sure to reference the applicable language of the code.  See the following examples:

### HTML Code
**Before:**
````markdown
`<button accesskey="b">Important Button</button>`
````
**After:**
````markdown
```html
<button accesskey="b">Important Button</button>
```
````

### CSS Code
**Before:**
````markdown
`animation-iteration-count: 3;`
````
**After:**
````markdown
```css
animation-iteration-count: 3;
```
````

### JavaScript Code
**Before:**
````markdown
`myVar = myVar * 5;`
````
**After:**
````markdown
```js
myVar = myVar * 5;
```
````

### JSX Code
**Before:**
````markdown
`<div style={{color: "yellow", fontSize: 16}}>Mellow Yellow</div>`
````
**After:**
````markdown
```jsx
<div style={{color: "yellow", fontSize: 16}}>Mellow Yellow</div>
```
````

**Tasks:**
- [x] Replace any single inline code blocks with characters at end with multi-line code blocks (see PR #41498)
- [ ] Replace all single inline code blocks with multi-line code blocks by creating a separate PRs for each certification affected.
  - [x] Responsive Web Design - 46 code blocks in 36 challenges (assigned to @Sembauke)
  - [x] JavaScript Algorithms and Data Structures - 35 code blocks in 25 challenges (assigned to @ieahleen)
  - [x] Front End Libraries - 28 code blocks in 25 challenges(assigned to @LaurentLabine)
  - [x] Data Visualization - 9 code blocks in 9 challenges (assigned to ???)
  - [x] Coding Interview Prep - 25 code blocks in 9 files (assigned to ???)
  
  **To get this task accomplished quickly, we are fine with multiple contributors taking on this issue.  Please let us know which section(s) you plan to create PRs for, so others will know not to work on those sections. We are limiting this issue to contributors who have already contributed in the past.**

**Comment by ieahleen** [comment]
I can help with this,, I can do JavaScript

**Comment by Sembauke** [comment]
I can help with the Responsive Web Design one

**Comment by LaurentLabine** [comment]
I'll go ahead and attack the Front End one!

**Comment by ieahleen** [comment]
if someone else wants to do the JS one, I have not been able to yet, my dev environment is not behaving nicely

**Comment by Sembauke** [comment]
> if someone else wants to do the JS one, I have not been able to yet, my dev environment is not behaving nicely

Take your time @ieahleen :)

**Comment by LaurentLabine** [comment]
Maybe I can redeem myself for the few mistakes i've made...  Do you need help with setting up?  What is the issue you are having?  Maybe I can help?

**Comment by ieahleen** [comment]
@LaurentLabine GitPod is having issues, I will try again tomorrow, for today I'm stopping here

**Comment by LaurentLabine** [comment]
Ahh Alright I cannot assist you then I have set it up using VSCode and downloaded all the code locally ...  Tomorrow is another day! :)

**Comment by LaurentLabine** [comment]
I'll go ahead and take on Data Vis and Coding Interview Prep

**Comment by RandellDawson** [comment]
@ieahleen In an effort to get this issue closed, I created PR (#41576).

**Comment by nhcarrigan** [comment]
When that PR merges, we should be good to close this right?

**Comment by RandellDawson** [comment]
@nhcarrigan Once mine is merged, the issue can be closed.

**Comment by RandellDawson** [comment]
Closing this issue as all related PRs have been merged.
