### ISSUE TITLE
DEV: Straightening Out Challenge Meta/Info

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/freeCodeCamp#41563]
**Background**
Working on features like #41147 and #39695 has pointed out an issue around the current meta related to _challenges_ and _certificates_.

**Meeting with Ahmad and Oliver**:
- [x] Look into renaming `superBlock` (with `-v7`) -> `certSlug` (resolved in #41738)
- [ ] Scrape off unused `.md` files; look into using `.json`
- [x] Refactor using type schema for working in the components (resolved with TS)
- [ ] Change `challengeType` into descriptive keys/values
- Could be better to use `id`s for majority of logic
- Look into linking a challenge to a `certificateId`

**Problems**
- The above affects the routing, display names, and general logic checking:
  - Routes to certificates use the `v7` naming
  - Visible superBlock text uses the dashed name
  - Checking whether or not a Camper can claim a certificate (and similar checks) is done through a mixture of meta.
- Some challenges/sections have meta defined, others are missing them:
  - `v7` superblocks are missing `name` property values.
  ```
  isSciCompPyCertV7: {
    id: '5e44431b903586ffb414c951',
    tests: [ [Object], [Object], [Object], [Object], [Object] ],
    name: undefined,
    challengeType: 7
  },
  ```
- The `title` property either includes words like:
  - "Responsive Web Design"
  - "Responsive Web Design Projects"
  - "Responsive Web Design Certification"
- Current state of `superBlock` in `markdownRemark`:
This query:
```graphql
allMarkdownRemark {
  nodes {
    frontmatter {
      superBlock
      title
    }
  }
}
```
Produces this:
```
{
  "frontmatter": {
    "superBlock": "machine-learning-with-python",
    "title": "Machine Learning with Python"
  }
},
{
  "frontmatter": {
    "superBlock": "APIs and Microservices",
    "title": "Introduction to the Managing Packages with npm Challenges"
  }
},
```

Once the Markdown meta is straightened out, the graph queries can be relied on for majority of block/challenge logic.

**Comment by ShaunSHamilton** [comment]
To drive my point home, I have found a bug in `CertChallenge.js`: #41564
