### ISSUE TITLE
UI Components Library

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#41580]
###  Problem:
Currently our HTML and CSS consist of the followings:
- A custom bootstrap 3 minified stylesheet injected in the head. 
- React-boostrap component library.
- Custom styles to re-write the bootstrap styles due to changes in design style guide.

As a result, we would need to remove a lot of the unused styles, overwrites, and find a better way to manage our components.

### Solution:
We should create our own component library that uses Storybook (isolate the components and document them) and tailwindCSS (style each component) and make sure they meet the [web accessibility requirements](https://www.w3.org/WAI/standards-guidelines/wcag/).

---

I would roughly break the project down into smaller tasks, and the list can be adjusted as we go:
- [x] Setup Storybook - https://github.com/freeCodeCamp/freeCodeCamp/pull/41920
- [ ] Setup Tailwind CSS 
  - [x] Basic Tailwind config - https://github.com/freeCodeCamp/freeCodeCamp/pull/42153
  - [x] Add color tokens to tailwind config (split to issue https://github.com/freeCodeCamp/freeCodeCamp/issues/42186 for further discussion) - https://github.com/freeCodeCamp/freeCodeCamp/pull/42388
  - [ ] Support dark mode #43616
- [x] Setup React Testing Library and its ESLint plugins - https://github.com/freeCodeCamp/freeCodeCamp/pull/42221
- [x] Setup TypeScript - #43541
- [x] Setup Prettier & other ESLint rules - https://github.com/freeCodeCamp/freeCodeCamp/pull/42818
- [ ] Setup css linter for custom CSS - related https://github.com/freeCodeCamp/freeCodeCamp/issues/16445
- [ ] Package build and publication setup 
  - [x] Setup Bundler (rollup/webpack/parcel) - https://github.com/freeCodeCamp/freeCodeCamp/pull/42549
  - [ ] Setup Publication (not for now)
- [ ] Write a guide for component development - @huyenltnguyen
- [ ] Build the following components
  - [ ] Alert #43835
  - [ ] Button - @huyenltnguyen 
  - [ ] Col
  - [ ] ControlLabel
  - [ ] DropdownButton (maybe consider using [Headless UI's Menu](https://headlessui.dev/react/menu))
  - [ ] Form
  - [ ] FormControl
  - [ ] FormGroup
  - [ ] Grid
  - [ ] HelpBlock
  - [ ] Image
  - [ ] Media
  - [ ] MenuItem
  - [ ] Modal (maybe consider using [Headless UI's Dialog](https://headlessui.dev/react/dialog))
  - [ ] Panel
  - [ ] Row
  - [ ] Tab
  - [ ] TabPane
  - [ ] Tabs
  - [ ] Table
  - [ ] ToggleButton (maybe consider using [Headless UI's Switch](https://headlessui.dev/react/switch))
  - [ ] ToggleButtonGroup
- [ ] Remove the ToggleButton in `/components/helpers` and replace it with the one above (? - I'm not sure, I haven't looked at the code closely, but I guess maybe there is a reason to split them)
- [ ] Use `npm-link` to link the ui folder with /client
- [ ] Replace `react-bootstrap` components with our own, one component at a time
- [ ] Audit and clean up any unused CSS code
- [ ] Remove `@freecodecamp/react-bootstrap` as a dependency
- [ ] Remove the bootstrap stylesheet injection
- [ ] Remove all CSS from Learn 
---
Lists were borrowed from @huyenltnguyen's comment below.

**Comment by Sembauke** [comment]
TailwindCSS: https://tailwindcss.com/docs/guides/create-react-app
StoryBook: https://storybook.js.org/docs/react/get-started/introduction

**Comment by raisedadead** [comment]
Should this issue be consolidated back into https://github.com/freeCodeCamp/freeCodeCamp/issues/16445

**Comment by ahmadabdolsaheb** [comment]
For that we would use stylelint which would enforce a common css style. I would keep both issues separate, but link them since they are related.

**Comment by prohackerzzz** [comment]
Can you please share some screenshots and elaborate more on this issue .I'm a newbie trying to contribute for the first time. Can you please help me??

**Comment by Sembauke** [comment]
> Can you please share some screenshots and elaborate more on this issue .I'm a newbie trying to contribute for the first time. Can you please help me??

Hey @prohackerzzz,
This isn't really an issue it's rather an improvement of the codebase. You can check out the links I posted to familiarize yourself with the documentation. You may be able to contribute to this later.

**Comment by ahmadabdolsaheb** [comment]
@prohackerzzz, I think once we have replaced a couple of the components, it would be easer to contribute as a first timer then.

**Comment by ahmadabdolsaheb** [comment]
It seems like there is a catch with working on the components one by one.
If we replace only one component, we would need to keep the injected bootstrap to keep the other components styled. 
That would result in writing additional bootstrap rewrites for the new component.

**Comment by huyenltnguyen** [comment]
@ahmadabdolsaheb I guess we could just build a set of new components first, then we could do incremental migrations when we deem they are ready.

Do we plan to use the components on other platforms too (code radio, news,...) or they will be /learn components only?

**Comment by gracewest333** [comment]
Hi, I am also a newbie who would love to help on this issue.  @huyenltnguyen I think that's a good idea to do it incrementally.

**Comment by ahmadabdolsaheb** [comment]
> @ahmadabdolsaheb I guess we could just build a set of new components first, then we could do incremental migrations when we deem they are ready.

@huyenltnguyen, I think here is the plan moving forward if we are planning to do incremental migration.

- The base styles should not be set in tailwindCSS since they include normalizers that also exits in bootstrap. ( we could add _base_ after removing bootstrap completely)
- Inject tailwindCSS after other stylesheets in head it rewrites other styles.( We should check the performance implications of adding tailwind while other styles are still injected)
- Keep customizations to the minimum ( stick to defaults as much as possible which will help with maintenance down the line ) 
- For every react-bootstrap component used, we should create a tailwindCSS styled storybook component.
- Easier to migrate and commonly used components take precedence in migration over harder to migrate and less commonly used ones.
- After couple of components are migrated and we gained more experience, we can revisit the battle plan and see if we could use scripts to speed up the migration.

This is a great read: https://dev.to/nejremeslnici/migrating-tachyons-to-tailwind-css-part-i-ich

Please let me what you think.

> Do we plan to use the components on other platforms too (code radio, news,...) or they will be /learn components only?
You are asking for the storybook structure?

Eventually we can reuse components across platforms; however, it is best to think about this component library built for learn at the moment to limit the scope of the migration.

Coderadio has very specific UI needs and not sure how modularity would improve it. Going headless with news is in the works but the use of client technologies are not finalized yet. 

Ideally learn and news will have similar ui elements (walls of text, grid system, etc) and both could pull from storybook in the future.

**Comment by JoshuaPelealu** [comment]
I have worked with Storybooks before. I have used tailwind with Storybooks and Svelte, but I'm sure it can be changed into tailwind and React easily.

**Comment by huyenltnguyen** [comment]
@ahmadabdolsaheb Thanks a lot! That sounds like a great plan. Now that it is up to us to be responsible for the components' HTML, what I would add as a criteria to our components is that they should be accessible and meet web accessibility requirements (https://www.w3.org/WAI/standards-guidelines/wcag/). 

Here is the list of components that we are pulling from `@freecodecamp/react-bootstrap`:
- Alert
- Button
- Col
- ControlLabel
- DropdownButton
- Form
- FormControl
- FormGroup
- Grid
- HelpBlock
- Image
- ListGroup
- ListGroupItem
- Media
- MenuItem
- Modal
- Panel
- Row
- Tab
- TabPane
- Tabs
- Table
- ToggleButton
- ToggleButtonGroup

---

I would roughly break the project down into smaller tasks, and the list can be adjusted as we go:
- [ ] Setup Storybook and Tailwind CSS
- [ ] Build the following components one by one
  - [ ] Alert
  - [ ] Button
  - [ ] Col
  - [ ] ControlLabel
  - [ ] DropdownButton
  - [ ] Form
  - [ ] FormControl
  - [ ] FormGroup
  - [ ] Grid
  - [ ] HelpBlock
  - [ ] Image
  - [ ] Media
  - [ ] MenuItem
  - [ ] Modal
  - [ ] Panel
  - [ ] Row
  - [ ] Tab
  - [ ] TabPane
  - [ ] Tabs
  - [ ] Table
  - [ ] ToggleButton
  - [ ] ToggleButtonGroup
- [ ] Remove the ToggleButton in `/components/helpers` and replace it with the one above (? - I'm not sure, I haven't looked at the code closely, so I guess maybe there is a reason to split them)
- [ ] Replace `react-bootstrap` components with our own, one component at a time
- [ ] Audit and clean up any unused CSS code
- [ ] Remove `@freecodecamp/react-bootstrap` as a dependency
- [ ] Remove the bootstrap stylesheet injection

---

For the component to-do list, I noted them down in alphabetical order, but I'm sure you have a different order in mind with the components' priority, so please help me to adjust it. If the list misses anything please help add them in as well.

**Comment by JoshuaPelealu** [comment]
>  Inject tailwindCSS after other stylesheets in head it rewrites other styles.( We should check the performance implications of adding tailwind while other styles are still injected )

Tailwind injection are typically very fast on production because as we know it, it will shake the tree and only inject what we need. While from my OWN experience and others, injecting tailwind into dev, will take longer because it doesn't treeshake on dev.

**Comment by ahmadabdolsaheb** [comment]
> Tailwind injection are typically very fast on production because as we know it, it will shake the tree and only inject what we need. While from my OWN experience and others, injecting tailwind into dev, will take longer because it doesn't treeshake on dev.

You are correct. TailwindCSS uses PurgeCSS to get rid of unused CSS.

> One question I have is does FCC uses Bootstrap or TailwindCSS, because AFAIK it uses bootstrap right?
> 
> If so, why are we using tailwindcss on storybook?

We are currently using bootsttrap; however, it comes with design decisions that we had to overwrite over time.

**Comment by ahmadabdolsaheb** [comment]
@huyenltnguyen,  thanks for the initial storybook setup. Looking forward to the tailwind, RTL, Package publication, and including the first component into learn. 

Generally speaking, performance is one of the main considerations for this migration. 
As demonstrated in the webpack analyzer, react-bootstrap and react-overlay( used in bootstrap ) are taking a large part of the app JS chunk which is what we serve on initial load. 

Optimizing our component library will help us reduce the size of that chunk and improve our SEO down the line.

![image](https://user-images.githubusercontent.com/4591597/117810762-78534c80-b268-11eb-8090-68e69691e35c.png)

**Comment by SAJJAD330** [comment]
Can we talk in whatsup .  My whatsup +923409094330.

On Tuesday, 11 May 2021, Ahmad Abdolsaheb ***@***.***> wrote:
> @huyenltnguyen, thanks for the initial storybook setup. Looking forward
to the tailwind, RTL, Package publication, and including the first
component into learn.
>
> Generally speaking, performance is one of the main considerations for
this migration.
> As demonstrated in the webpack analyzer, react-bootstrap and
react-overlay( used in bootstrap ) are taking a large part of the app JS
chunk which is what we serve on initial load.
>
> Optimizing our component library will help us reduce the size of that
chunk and improve our SEO down the line.
>
> <
https://ci3.googleusercontent.com/proxy/I-2B8Q0yj2DKsggmeXwp28vwOMb1xb0sMKqwHNN4uU8XthPE1hTBN5ytqhQzxmPR5gQlOF8Uc6pf-fcCmOeBcTyO4_7iSTKG_jNblQx88V2s0iKsNkmeN8Rm_E1djmZtFN8jpnF-SmWEiqDUOlnCQ9dIUEEccGw=s0-d-e1-ft#https://user-images.githubusercontent.com/4591597/117810762-78534c80-b268-11eb-8090-68e69691e35c.png
>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci6.googleusercontent.com/proxy/j_DKX9PX8JU0ortHurn457VCYD9PtlpgOlSHj8LzNN3F-a7Qg4_U_fc66tT2VXgMStuXvs8uNQfeTt1bUw_R8_t8_UoNzosGkoKExmnhfaR5sYx0ICvQ_msaz6TESMAlZwlf3XByqajH0gNDGIuIT0MBda52IopiOiIvNQIGU8ZNV-WvzJUUiFgGtKZdJ6oC7nyOAug6sTFEwvhuLDCCq6AiyNzUGATXKW98yAJiGQ=s0-d-e1-ft#https://github.com/notifications/beacon/AS37M3T4WFGLZE2AMHL7RDTTNEL4JA5CNFSM4ZZ7HE52YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOGH4BOCA.gif>

**Comment by ahmadabdolsaheb** [comment]
@mrugesh, would you like to have the component library completely isolated as an npm package?

**Comment by raisedadead** [comment]
Thanks for asking, I have tried and articulated the intent here: https://github.com/freeCodeCamp/freeCodeCamp/pull/41920#pullrequestreview-644913778, a TL;DR version is yes to isolation and a probable no to a npm package (just for now atleast)

**Comment by ahmadabdolsaheb** [comment]
Since we are moving forward with Typescript, it might be beneficial to scaffold the entire storybook setup using a TS package developer CLI such as [TSDX](https://tsdx.io/), that has Rollup, Jest, tsconfig, TSLint, storybook, etc out of the box. We would just need to add TailwindCSS config and RTL on the top. Thoughts?

**Comment by ojeytonwilliams** [comment]
I'm not sure about TSDX.

Firstly, it uses TSLint which was deprecated back in 2019 - TSLint's maintainers recommend people use typescript-eslint now.  Also, if we wanted to move on from it, is there an easy way to bail out?

**Comment by raisedadead** [comment]
As a general rule, we want to avoid tools that are opinionated.

**Comment by ahmadabdolsaheb** [comment]
I see, just to clarify we want the followings:
- We want an isolated testable TS module with its independent bundler.
- We would like the component library module to be the single source for the styles for learn.

**Comment by raisedadead** [comment]
Yes, we would probably prefer a bundler like webpack that we already have experience with but not necessarily married to.

**Comment by ahmadabdolsaheb** [comment]
One of the component library documentation patterns include adding the styleguide as the storybook first page.

This might be a good strategy for us to adopt where we could add our styleguide to our storybook, build and deploy it at https://design-style-guide.freecodecamp.org/ and have it be the single source of truth for design.

**Comment by huyenltnguyen** [comment]
@ahmadabdolsaheb Do you see https://design-style-guide.freecodecamp.org/ as a simple Storybook page, or will it be a documentation page like [Material UI](https://material-ui.com/) or [Tailwind](https://tailwindcss.com/docs)?

I personally prefer documentation page as it is more structured and we can have more content about our design system rather than just component-specific. But I'm obviously painting a far future here.

Could we for now deploy and host Storybook at `https://design-style-guide.freecodecamp.org/storybook`?

**Comment by raisedadead** [comment]
Actually, melding all of these resources under the `https://contribute.freecodecamp.org` might be a good idea. It should be possible for us to host this something along these lines:

https://contribute.freecodecamp.org --> Contributing Home/Landing Page
https://contribute.freecodecamp.org/translate --> Translations
https://contribute.freecodecamp.org/design --> UI Design Style Guide (redirecting the current guide here)
https://contribute.freecodecamp.org/design/storybook --> The storybook.

etc., you see the idea.

If you both agree, I will set up some configs (on our existing servers) to make this happen.

**Comment by huyenltnguyen** [comment]
That works for me. Although we will need to add some extra publish and deploy config to Storybook (I didn't include it in the initial setup).

I can take a look at it, but I'm in the middle of other setup work right now, so it would be great if anyone here can help us with this 🙂 

The [doc](https://storybook.js.org/docs/react/workflows/publish-storybook) mentions Chromatic as a publishing service. While it is a nice tool that helps automate a lot of workflows, I don't think we really need it, and we can look at [storybook-deployer](https://github.com/storybookjs/storybook-deployer) instead (this is also mentioned in the doc).

**Comment by ahmadabdolsaheb** [comment]
@huyenltnguyen, since storybook is partly a documentation tool, we could take advantage of that and host our the design style guide inside the storybook and have the whole thing live in https://contribute.freecodecamp.org/design. That way we could add more documentation and turn it into a design system. That being said, I do not have a strong preference either way.

ex.
https://developers.grafana.com/ui/latest/
http://storybook.anyvision.co/

ref.
https://storybook.js.org/tutorials/design-systems-for-developers/

**Comment by Nirajn2311** [comment]
I like Ahmad's idea as it keeps all design related documentation in one link. Also that will help out the new contributors as they don't have to search in two different places.

**Comment by samarmohan** [comment]
How is the progress on this?

**Comment by ahmadabdolsaheb** [comment]
It is going well, one of the tasks that can be done in parallel is setting up TS for the component library if you are interested.

**Comment by ahmadabdolsaheb** [comment]
@samarmohan, t is going well. One of the tasks that can be done in parallel is setting up TS for the component library if you are interested.

**Comment by thinklikeadesigner** [comment]
Have you heard of bit.dev? it's free for opensource, and you can store your actual components library there, with versioning and everything. You can keep everything in one place, and it works great with storybook too

**Comment by thinklikeadesigner** [comment]
Have you heard of bit.dev? it's free for opensource, and you can store your actual components library there, with versioning and everything. You can keep everything in one place, and it works great with storybook too

You just import the components into your project, as if they were from any other UI library, so it's like you have your own design system in the cloud that you can pull your components from.

https://www.machineservant.com/blog/2020-11-05-bit-dev-storybook/

**Comment by ahmadabdolsaheb** [comment]
Thanks for the suggestion. I think bit.dev would be ideal for larger component libraries. We have a limited number of pre-designed components that need to be migrated from bootstrap.

**Comment by raisedadead** [comment]
Hey @huyenltnguyen I have been trying to reach you, could you check your DM on chat or your email (including spam) when you get a chance. Thanks.

**Comment by ashiskumar-1999** [comment]
Hey @raisedadead, Can I take the Modal component?

**Comment by raisedadead** [comment]
Thanks for reaching out @ashiskumar-1999, I recommend you join our contributors chat and get in touch with @huyenltnguyen who is leading the effort. For the most part you should be good though.

**Comment by ashiskumar-1999** [comment]
Hey @huyenltnguyen, Mind if I can ask for the link of the channel for contributors chat?
Also, what's your thought on taking myself the responsibilities of the Modal component?

**Comment by raisedadead** [comment]
Go ahead and give this a quick read: https://contribute.freecodecamp.org - this should get you started

**Comment by ashiskumar-1999** [comment]
Thanks@raisedadead !😊

**Comment by huyenltnguyen** [comment]
Hi @ashiskumar-1999, thanks for giving us a hand!

We have mostly completed the component library setup. I plan to start first with the Button component and try to document the development process to help onboard other contributors. My schedule has been a bit crazy lately, but I think I would have time for that in September.

The Modal component might be a bit complicated with the rendering in a React Portal, as well as the accessibility aspect (elements in the background should be `aria-hidden` so that screen reader users know what to focus).

I haven't done enough research on this to propose an approach, but our ultimate goal is to reduce the dependence on third-party libraries, so we would either build our components from scratch, or find a light-weight library for complex components (Modal is one of them).

I would recommend going through the existing modals in our codebase first and find the patterns / use cases, so that we know what props the Modal component should support.

**Comment by ashiskumar-1999** [comment]
Hey @huyenltnguyen , 
Cool. I am going through it. If you may Can I take responsibility to do it? 
If my Modal will match your requirement then you can merge it with your codebase or else you can simply close it.

**Comment by ashiskumar-1999** [comment]
You can also recommend sone component so that I can start the development.

**Comment by ashiskumar-1999** [comment]
Hey @huyenltnguyen, I have gone through the codebases of other component libraries. They all use the React portal. I can do it.

**Comment by mansijain980** [comment]
I want to work on image and toggle button component, Its urgent to contribute for me. Please reply asap.

**Comment by ahmadabdolsaheb** [comment]
@mansijain980, thank you for your interest.  If you are in a hurry, I highly recommend adding the color tokens to the config (https://github.com/freeCodeCamp/freeCodeCamp/issues/42186) which is one of the setup steps needed before we could start working on the developing the components.

Additionally, the image component seems straight forward and does not require the theme support which is not implemented yet. Feel free to proceed with creating the image element. Please make sure to review a11y best practices for the image element and document the process of component creation in your pr.

@mansijain980, thank you for your research. Let me do a little bit of research and get back to you on the ways we could move forward on developing tailwind overlay components.

**Comment by ahmadabdolsaheb** [comment]
@ashiskumar-1999, I was wondering if you could share the links to the component libraries you looked into for the modal component? 
Also did you have a change to look into tailwindUI overlays for samples of modal implementation using tailwind? https://tailwindui.com/#product-application-ui

**Comment by ashiskumar-1999** [comment]
@ahmadabdolsaheb, I looked into the Carbon design system (https://www.carbondesignsystem.com/components/modal/usage/), Chakra-UI (https://chakra-ui.com/docs/overlay/modal) as a reference. About the TailwindUI overlays part, yes, I have gone through the code samples on the website.

**Comment by hamzawaleed0102** [comment]
@ahmadabdolsaheb @huyenltnguyen 
I'm a SSE but new to open source, let me know if I can contribute in any way.

**Comment by hamzawaleed0102** [comment]
Yes @ahmadabdolsaheb  that would be great 🎉. Please share a bit more details to help me get started easily.

**Comment by ahmadabdolsaheb** [comment]
We have a component library at https://github.com/freeCodeCamp/freeCodeCamp/tree/main/tools/ui-components
that uses storybook for managing and documenting UI components. It uses tailwind to style those components and rollup to bundle them. 

A good starting point would be reading the TS related Storybook docs: https://storybook.js.org/docs/react/configure/typescript

**Comment by hamzawaleed0102** [comment]
Thanks @ahmadabdolsaheb 
Let me go through the docs and get back to you on this, most probably with a draft PR.

**Comment by hamzawaleed0102** [comment]
@ahmadabdolsaheb Here's the [link to the PR,](https://github.com/freeCodeCamp/freeCodeCamp/pull/43541) looking forward to your valuable feedback.

**Comment by hamzawaleed0102** [comment]
@ahmadabdolsaheb I enjoyed working on TS configuration for UI components library. I'm up for any other ticket.

**Comment by RJamesMaier** [comment]
Hey! I would love to help. I enjoy working with TS and love working on frontend components. Where can I help?

**Comment by RJamesMaier** [comment]
Awesome thank you!

**Comment by huyenltnguyen** [comment]
Hey friends 👋 

First of all, I'm sorry for being absent for a very long time and blocking the work. Covid hit and left me with mental bumps and bruises. I will need some time to get the balance back, but will try to be more responsive here as well as in the chat. 

As @ahmadabdolsaheb mentioned, we will need to gather the specs for each component before implementing them. The requirements will be slightly different depending on the complexity of the components, but I think the following questions need to be answered overall:
- How the component is being used in FCC apps? For example, does modal always have a header? - Knowing all the use cases allow us have a better idea on what props the component needs to support.
- How is the component being themed? - We will need to revisit our color swatch, so having this information will be helpful in defining the color standard.
- What is the HTML element the component renders under the hood? - This is so that we can apply the same implementation, or identify any incorrect element usage and address it in the new component. We should also pay attention to other HTML attributes (`required`, `disabled`, `aria-describedby`,...)
- What HTML attributes get added/removed when the component changes its state? For example, what attributes get added to the `input` when it is marked required, or is disabled? - This is extended from the question above, but the attributes are not always present unless the component is in a specific state.

I think I have more to add, but I will need to sit down to have a more comprehensive guide (this is part of the documentation task that I keep failing to commit). I know this is quite overwhelming, especially the accessibility part, but I believe this is a right thing to do. Having a11y in mind now will enables us to have better implementation approaches in the beginning, rather than trying to shift the implementation later as a11y being an after-thought. We don't need to get it right the first time, but just try to take into consideration. Btw, even Material UI can't claim that their components are 100% accessible (see [this PR](https://github.com/mui-org/material-ui/pull/27826)).

Also, I was thinking about opening an issue for each component, so that we can keep the discussion in one place, but it's up to you guys 🙂.

Feel free to send PRs out if you think they are ready, and perhaps /cc me in there for visibility. I will try, but I don't think I can review them in a timely fashion, and I know it is Hacktoberfest, so I don't want to ruin it for you. I'll trust the core maintainers with the decision to merge the changes. I would rather see some movements in the component library rather than leaving it stale.

Looking forwards to your contributions. Stay safe, stay healthy, and happy coding!

---

There are a lot of component libraries out there for us to use as references, I'm linking some that I find helpful for me when I need to look for component guidelines and a11y best practices:
- https://www.carbondesignsystem.com/
- https://mui.com/getting-started/usage/
- https://spectrum.adobe.com/

One interesting thing I recently found is that there are a lot of governments that have their own design system page, and they are open source ❤️ (and tax money well spent!):
- https://designsystem.digital.gov/
- https://design-system.service.gov.uk/
- https://designsystem.gov.au/
- https://design.gccollab.ca/

**Comment by sitek94** [comment]
Hey everyone! 👋 

I've been working a bit on alert component, and I've just opened a draft PR (#43835). I would really appreciate your feedback!

**Comment by JoeTurnerIO** [comment]
I have experience building UI component libraries and would like to contribute. Are there any mocks for these components?

**Comment by adsingh14** [comment]
I would like to contribute.

**Comment by Ismailtlem** [comment]
Hi everyone,
I am interested in taking part in this effort, I've made a Draft PR for the image component. Any feedback would be greatly appreciated
