### ISSUE TITLE
Bugs in the next branch (TypeScript migration)

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#42660]
Please add any problems with https://beta.freecodecamp.dev/learn to this issue.

Condensed list of issues below:
- [x] [completion modal not showing up](https://github.com/freeCodeCamp/freeCodeCamp/issues/42660#issuecomment-871404587): #42685
- [x] [closing donation modal error: unrelated to migration](https://github.com/freeCodeCamp/freeCodeCamp/issues/42660#issuecomment-869811119)
- [ ] [private 'about' info shows up in profile caching issue](https://github.com/freeCodeCamp/freeCodeCamp/issues/42660#issuecomment-869814105)
- [ ] ["checker is not a function" error in console when loading editor](https://github.com/freeCodeCamp/freeCodeCamp/issues/42660#issuecomment-870791722)
- [x] ["Input is not HTMLInputElement" error when submitting URL's by tabbing to the submit button](https://github.com/freeCodeCamp/freeCodeCamp/issues/42660#issuecomment-871482595)

**Comment by ShaunSHamilton** [comment]
Closing donation modal produces this error in the console:
![image](https://user-images.githubusercontent.com/51722130/123668318-e3fe7280-d832-11eb-8ab8-e1146002e15d.png)

**Comment by ojeytonwilliams** [comment]
Private About descriptions appear in the Profile:
![image](https://user-images.githubusercontent.com/15801806/123668668-9df9dc80-d83b-11eb-9dde-ec649df2a6fe.png)

this is very flaky.  It seems to come and go.

**Comment by ShaunSHamilton** [comment]
The private `about` looks like a React cache issue - refreshing the page consistently makes it disappear for me.

**Comment by ojeytonwilliams** [comment]
I couldn't reproduce it reliable on beta and not at all on .dev.  So, yes, it definitely sounds like a caching problem, but it might be a new one.

**Comment by ShaunSHamilton** [comment]
Editor throws error in console, on render (ref https://github.com/freeCodeCamp/freeCodeCamp/pull/42651):
```
Warning: Failed prop type: checker is not a function
    in DesktopLayout (created by ShowClassic)
    in ShowClassic (created by withI18nextTranslation(ShowClassic))
    in withI18nextTranslation(ShowClassic) (created by Connect(withI18nextTranslation(ShowClassic)))
    in Connect(withI18nextTranslation(ShowClassic)) (created by PageRenderer)
    in div (created by DefaultLayout)
    in div (created by DefaultLayout)
    in DefaultLayout (created by withI18nextTranslation(DefaultLayout))
```

**Comment by raisedadead** [comment]
I do not get errors on the beta for donate modal. Please add elaborate steps to repro?

![image](https://user-images.githubusercontent.com/1884376/123844077-3a051000-d930-11eb-93c1-4099d04a1278.png)

**Comment by ShaunSHamilton** [comment]
@raisedadead I get the errors any time I click the _Ask me later_ button.

Also, I realise I am being redirected to `freecodecamp.dev`, seemingly randomly. I get the errors there as well.

**Comment by raisedadead** [comment]
I am still unable to reproduce. I would appreciate some detailed steps to debug and see the console logs. 

> I get the errors any time I click the Ask me later button.

So you mean you are not seeing the errors with donate modal anymore? Are these the same errors as the modal? 

> I realise I am being redirected to freecodecamp.dev, seemingly randomly.

Again I will need a detailed sequence of steps to reproduce, but it is possible that you can get that. The reason being we haven't defined "beta.freecodecamp.dev" as the "home" anywhere in code. Meaning, some routing will default to the TLD as you might have been experiencing. 

That said, it's an issue that we would want to keep for the QA cycle later on staging.

**Comment by ShaunSHamilton** [comment]
To reproduce:
1) Complete enough challenges for Donation Modal to appear
2) Click on _Ask me later_ (to close modal)
3) See in console for error:
```
react_devtools_backend.js:2560 unhandled_error {err: "Error: Detected container element removed from DOM…amp.dev/framework-7ca6da6cd38fb917112c.js:2:46441", timestamp: "1624991551882", referer: "www.freecodecamp.dev", uid: "uid_7bcc0447cc_mtg6mzi6mjg", env: "sandbox"}
 Uncaught Error: Detected container element removed from DOM
    at VM184 js:2
    at VM184 js:2
    at l (VM184 js:2)
    at vo (react-dom.production.min.js:221)
    at ku (react-dom.production.min.js:253)
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at $l (react-dom.production.min.js:122)
    at wu (react-dom.production.min.js:248)
    at ou (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
```

**Comment by ShaunSHamilton** [comment]
I have managed to reproduce this many times, and even disabled React Devtools extension for good measure.

https://user-images.githubusercontent.com/51722130/123864577-d3c5c080-d922-11eb-99d3-32e132dba8c5.mp4

---

Also, it seems, if I click on _Ask me later_ , the DonationModal will not reappear, unless I refresh the page. That is, after closing the modal, I can complete 30+ lessons without it reappearing - My understanding is it should reappear:
- If a block has been completed
- 10 lessons have been completed

**Comment by scissorsneedfoodtoo** [comment]
I took a look at the donation modal and was able to reproduce that error message on both beta.freecodecamp.dev and www.freecodecamp.dev.

It seems like an existing issue with the PayPal script complaining about the container element being removed, and isn't due to the TS migration.

I haven't been able to reproduce the issue with the `DonationModal` not reappearing, though. So long as I complete new challenges, I can get the modal to reappear normally. If I redo challenges I've already completed, then the modal does not reappear every 10 lessons or when a block is completed.

Not sure if this is intended behavior or not, but it seems to work this way on both beta.freecodecamp.dev and www.freecodecamp.dev.

**Comment by raisedadead** [comment]
Thanks for the additional steps Shaun. Now that I have wiped my glasses, I have now been able to reproduce and see this consistently. 

I believe Kris is correct in his findings, I think we haven't configured PayPal's sandbox script environment to accept the test site as an origin correctly and hence the errors.

But, I was able to successfully make a donation and dismiss the modals - meaning the behaviour seems to be unaffected. So, I guess we are good?

**Comment by raisedadead** [comment]
The <kbd>Ctrl</kbd> + <kbd>Enter</kbd>, shortcuts work partially. That I am able to run tests using the shortcut, but I am unable to trigger the completion modal once all tests have passed.

The completion modal shows up only when the "Run the tests" button is clicked.

I think the shortcuts are flaky on the modal as well, that sometimes they move to the next challenge. But sometimes they are stuck.

Tested on a deployed commit as of this comment: 46fd785b381bae3c0b701f4d93b4d1566e2fc78c

**Comment by ShaunSHamilton** [comment]
@raisedadead Sounds related to the upcoming changes editor which specifically has the logic to only not show the modal when `Ctrl + Enter` is used.

**Comment by raisedadead** [comment]
Thanks for the quick debugginging, those bits should be reinstated. Do you know how?

**Comment by ShaunSHamilton** [comment]
>  Do you know how?

It is a bit confusing, as I am unsure where we are going with the upcoming changes. That is, typically, `frontend/Show.tsx` is used for these challenges, which directly opens the modal. However, now we are using `classic/Show.tsx`, the logic for frontend and backend is mixed.

Do we plan on removing `frontend/Show.tsx` and `backend/Show.tsx`, in favour of `classic/Show.tsx`?

**Comment by moT01** [comment]
Error in console when submitting URL's:
![Screen Shot 2021-06-30 at 10 00 03 AM](https://user-images.githubusercontent.com/20648924/123984172-0c4cb500-d98a-11eb-9e77-e6c8070e3bee.png)


Steps to reproduce:
- go to a challenge where you need to submit a URL. i.e. a cert project
- type in a URL to submit
- press tab to focus the "I've completed this challenge button"
- press enter to submit the challenge
- see error

**Comment by thecodingaviator** [comment]
@moT01 I'm unable to reproduce that

**Comment by Nirajn2311** [comment]
Same here, I couldn't also reproduce Toms bug.

**Comment by moT01** [comment]
@ShaunSHamilton found it, so I can't take credit. I was able to reproduce it on production and dev. I believe it's some sort of caching or storage issue. I wasn't able to reproduce on private browsing or a fresh browser.

**Comment by scissorsneedfoodtoo** [comment]
@moT01 and @ShaunSHamilton, I took a look and was able to reproduce that `Assertion failed: Input argument is not an HTMLInputElement` bug.

Turns out that it's probably related to the LastPass extension, at least in Chrome. I haven't tried it in Firefox yet.

Like @moT01 mentioned, I'm unable to reproduce the bug in an incognito window, or once I disable LastPass in my main window.

This thread has more information about possible workarounds and fixes: https://github.com/mui-org/material-ui/issues/14860

**Comment by ShaunSHamilton** [comment]
> Turns out that it's probably related to the LastPass extension, at least in Chrome.

@scissorsneedfoodtoo Ah... brilliant. Well done, for catching that.

**Comment by huyenltnguyen** [comment]
I'm not sure if this issue is related to the TS migration, but I helped a user to create their FCC account just moment ago, and I found that after the user entered the code and authenticated successfully, they could briefly see the introduction screen ([IntroDescription](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/components/Intro/components/IntroDescription.js)) for a few seconds before automatically got redirected to /learn.

**Comment by raisedadead** [comment]
Thanks, @huyenltnguyen we have actually pushed the changes live a few minutes ago. I am going to close this umbrella issue and we should start reporting and fixing issues independently. 

Can you log a fresh issue for the same?
