### ISSUE TITLE
Discourse-Learn Integration

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/freeCodeCamp#42837]
Following the addition of more badges to profiles, this issue discusses the possible integration of the Discourse API with `/learn`.

As Discourse comes with the API and GUI to create/grant badges, it would be most ideal to _seamlessly_ provide this functionality on a Camper's profile on `/learn`.

Possible Feature Additions (will do):
- [x] Display all current badges from `forum` to `/learn`
- [x] Use Discourse to upload/create i18n badges
- [x] Port _Top Contributor_ badges (years) over to Discourse
- [ ] Add `forum` account metrics to `/learn` (e.g. Number of hearts, number of question answers)

Implementation Details:
- Use associated email addresses for authentication
  - Some Campers use a separate email for forum and `/learn`
    - Allow Campers to manually associate forum account with `/learn`? ❌ 
  - Use OAuth to authenticate (match) Camper accounts ✔️ 
  - Will require API Key for at least email verification
- Which privacy settings to use for feature?
  - Use an existing setting (e.g. `profile`) ✔️ 
  - Automatically associate known email addresses? _Potentially require intervention on `/settings`
- Styling
  - How to display the badges on the profile?
    - At the very bottom ✔️ _low priority_
    - Probably provide collapsible functionality
    - Use Discourse-provided priority meta for order
    - Use Discourse-provided _favourites_ functionality for displaying Camper-chosen badges

**TODO**
- [x] Open initial PR
- [ ] Investigate SVG vs JPEG for creating badges
- [ ] Finalise authentication method

[Discourse Badges API Documentation](https://docs.discourse.org/#tag/Badges)

**Comment by ShaunSHamilton** [comment]
> Is this because of some unification?
Shouldn't there be new badges that correlate with the learning platform, if so which?

@Sembauke The main reason for this is the addition of i18n-related badges (once more is finalised, we can share specifics). So, to not re-create the wheel, we thought to use Discourse's API/GUI to create, store, and award the badges, but we also want to include them on the `freecodecamp.org` domain. So, nothing more than the stats from one to the other.

**Comment by ShaunSHamilton** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue: Track Discourse-Learn Integration](https://trello.com/c/aDOko7Kj/455-issue-track-discourse-learn-integration)

**Comment by ShaunSHamilton** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue: Track Discourse-Learn Integration](https://trello.com/c/aDOko7Kj/455-issue-track-discourse-learn-integration)
