### ISSUE TITLE
Curriculum refactor

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#43114]
- [ ] remove the markdown files in client/src/pages/learn
- [ ] remove the redundant parts of the curriculum/schema/challengeSchema.js
- [ ] check if the numbers in say: curriculum/challenges/english/01-responsive-web-design can be removed without requiring re-approval of translations.

**Comment by nhcarrigan** [comment]
For number 3, removing the numbers will require re-translation.

**Comment by moT01** [comment]
Related info: https://github.com/freeCodeCamp/freeCodeCamp/issues/41563

**Comment by raisedadead** [comment]
From https://github.com/freeCodeCamp/freeCodeCamp/pull/43353#issuecomment-910257506

> A couple of quick thoughts - looks like these are mostly the files in the 00-certificates folder. If none of the values are being displayed, do we need to be putting them on Crowdin to get translated? Seems like it might be okay to just keep them all in English so we don't have to keep re-translating them.
> 
> Maybe something to consider with a [curriculum refactor](https://github.com/freeCodeCamp/freeCodeCamp/issues/43114) would be to extract the info from these into a meta file or something and only have one version in English.

**Comment by nhcarrigan** [comment]
Some relevant conversation in #42902 for removing the numbers.

**Comment by ieahleen** [comment]
> Do you mean re-translation or re-approval? They should just need to be re-approved right?

to put it here, it will only needs to be re-approved if someone with manager access goes to Crowdin and use the _PRE-TRANSLATE from Translation Memory_ feature to retrieve all translations, then proofreaders will just need to double check and approve.

**Comment by Sembauke** [comment]
closing this as not planned. We should rethink this when we have time.
