### ISSUE TITLE
i18n: Python projects' instructions are not translatable

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#43836]
For these projects the instructions are in the README file inside the boilerplate, as such they are not translatable.

I propose to add a copy of the projects readme inside the project file in the main repo.

List of projects that need it:
### Scientific Computing with Python
- [x] Arithmetic formatter #43854 
- [x] Time Calculator #44152
- [x] Budget App #44125
- [x] Polygon Area Calculator #44152
- [x] Probability Calculator #44152

### Data Analysis with Python
- [X] Mean-Variance-Standard Deviation Calculator #44160
- [X] Demographic Data Analyzer #44160
- [X] Medical Data Visualizer #44160
- [X] Page View Time Series Visualizer #44160
- [X] Sea Level Predictor #44160

### Information Security  
- [x] Port Scanner #44241
- [x] SHA-1 Password Cracker #44241

### Machine Learning with Python 
- [ ] Rock Paper Scissors
- [ ] Cat and Dog Image Classifier
- [ ] Book Recommendation Engine using KNN
- [ ] Linear Regression Health Costs Calculator
- [ ] Neural Network SMS Text Classifier 

---

(Mods feel free to edit as needed)

**Comment by Sembauke** [comment]
CC: @nhcarrigan

**Comment by nhcarrigan** [comment]
Okay, I created https://github.com/freeCodeCamp/freeCodeCamp/pull/43854 as an example attempt so we can play with how this works.

My thoughts are:

- Currently challenge type 10 doesn't seem to support the `--instructions-- header. Might be something to poke @ojeytonwilliams about?
- We will likely want to remove the README from the projects in favour of the information on `/learn`, so we maintain a single source of truth.
- Once we are happy with the example PR, we should create a checklist here (similar to the typescript migration), allow folks to claim files, and open this up for contribution.

**Comment by nhcarrigan** [comment]
Yeah I think that's a solid approach.

**Comment by ieahleen** [comment]
The change to the boilerplate should wait for a website deployment, so that campers aren’t left without instructions
