### ISSUE TITLE
[beta] RWD Task List

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#44664]
## Task 1: Move RWD beta to live

- [x] Rename step files so they can be translated (https://github.com/freeCodeCamp/freeCodeCamp/pull/45146)
- [x] Update helper functions so they work with new filenames (https://github.com/freeCodeCamp/freeCodeCamp/pull/44769)
- [x] Enable uploading new files to crowdin (should work automatically after above two are merged)
- [x] Swap beta and legacy locations on the map (Leave as beta for now while other things are worked out) (https://github.com/freeCodeCamp/freeCodeCamp/pull/45865)

### Future Task: i18n RWD
After task 1 is complete, we can start translating the RWD projects. When ready...
- [x] Add new RWD to other i18n's

### MVP:
- [x] Add framework for new projects - aka challengeType 14 (#44505)
- [x] Allow saving to and loading from database  (#44700) - should be able to merge w/o affecting client
- [x] Moderator Dashboard
- [x] #44979
    - https://github.com/freeCodeCamp/freeCodeCamp/pull/45139
    - https://github.com/freeCodeCamp/freeCodeCamp/pull/45220
- [x] Make `ctrl+s` save to db (https://github.com/freeCodeCamp/freeCodeCamp/pull/45406)
- [x] Convert cert projects and tests to use new editor (#44564) - can’t merge/deploy until release, changes the actual projects - we still didn't conclude if we want to convert all 10 or just the new ones
    - Add solutions
    - I planned to add cypress tests on this PR for some of the related stuff above
- [x] add RWD beta cert to settings, making two RWD on settings page? Will it be a different cert or the same cert after we change the projects? (https://github.com/freeCodeCamp/freeCodeCamp/pull/45865)

### DESIRABLE:
- [x] Move demo projects to .rocks (https://github.com/freeCodeCamp/demo-projects/pull/206)
- [x] Make cert project UI on superBlock page better (#44771)
- [ ] Fix up UI issues described [in this review](https://github.com/freeCodeCamp/freeCodeCamp/pull/45220#pullrequestreview-891405091)
