### ISSUE TITLE
Implement Button component

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#45357]
## Current specs

- Border width: 3px
- Font: `Roboto Mono, monospace`
- Variants:
  - Primary
  - Info
  - Danger (on the Setting page)
  - Link (on the donation modal)
- Sizes: 
  - Large
  - Medium (default)
  - Small
- States:
  - Disabled
  - Hover state
- Button types:
  - `type="button"`
  - `type="submit"`
- Themes:
  - Light
  - Dark
- Can be a link (supports `href` prop)
- Can be used as a block (stretch)
- Supports text + icon
- Accepts ARIA attributes

### What's missing

- Loading state
- Focus outline
- Active state

### Screenshots

| Usage | Light theme | Dark theme |
| --- | --- | ---|
| Primary| <img width="776" alt="Screen Shot 2022-03-06 at 17 14 06" src="https://user-images.githubusercontent.com/25715018/156918749-41c5f287-b880-41a4-b8d0-8f619a4ef961.png"> | <img width="789" alt="Screen Shot 2022-03-06 at 17 13 43" src="https://user-images.githubusercontent.com/25715018/156918757-361449c7-8089-40a0-825c-30246b05c8ab.png"> |
| Primary hovered | <img width="775" alt="Screen Shot 2022-03-06 at 17 51 27" src="https://user-images.githubusercontent.com/25715018/156919909-cb047d73-cdd9-413f-89fe-ae3c203a2e22.png"> | <img width="777" alt="Screen Shot 2022-03-06 at 17 50 55" src="https://user-images.githubusercontent.com/25715018/156919919-82604770-c889-4313-b7fb-793a88377512.png"> |
| Primary disabled | <img width="768" alt="Screen Shot 2022-03-06 at 17 51 20" src="https://user-images.githubusercontent.com/25715018/156919932-4b08c8e8-0fba-41f7-bafa-77d1fba3c7d3.png"> | <img width="769" alt="Screen Shot 2022-03-06 at 17 51 08" src="https://user-images.githubusercontent.com/25715018/156919936-bd8c79a2-867e-465d-8278-ac4c509034b7.png"> |
| Danger | <img width="508" alt="Screen Shot 2022-03-06 at 17 21 12" src="https://user-images.githubusercontent.com/25715018/156919015-3e936ca6-f40a-4836-950f-a493f7a585f3.png"> | <img width="509" alt="Screen Shot 2022-03-06 at 17 21 46" src="https://user-images.githubusercontent.com/25715018/156919017-c10ce16e-944d-40e2-a8e9-711791b740e7.png"> |
| Danger hovered | <img width="508" alt="Screen Shot 2022-03-06 at 17 52 59" src="https://user-images.githubusercontent.com/25715018/156919988-8cc2cd02-6881-4310-8565-94fcfeb49c8d.png"> | <img width="509" alt="Screen Shot 2022-03-06 at 17 53 16" src="https://user-images.githubusercontent.com/25715018/156919995-67877456-1ad9-4160-ab1a-8a28ff6c9bb5.png"> |
| Link | <img width="164" alt="Screen Shot 2022-03-07 at 18 24 47" src="https://user-images.githubusercontent.com/25715018/157022505-b578cd18-7b5c-4bf7-bf59-218545da2f63.png"> | <img width="143" alt="Screen Shot 2022-03-07 at 18 27 00" src="https://user-images.githubusercontent.com/25715018/157022780-bd7c88d6-f88d-464a-ad17-a4c3aba29f5b.png"> |
| Link hovered | <img width="285" alt="Screen Shot 2022-03-07 at 18 24 41" src="https://user-images.githubusercontent.com/25715018/157022833-db610ccd-5b34-415b-94c4-be1d855c88e2.png"> | <img width="299" alt="Screen Shot 2022-03-07 at 18 27 06" src="https://user-images.githubusercontent.com/25715018/157022870-db2c4635-a2c3-45db-90bc-909bf8b9ec6c.png"> |
| Info | <img width="505" alt="Screen Shot 2022-03-26 at 18 51 45" src="https://user-images.githubusercontent.com/25715018/160238162-ea3afa03-123b-4b96-91bf-e4885cf1c9af.png"> | <img width="502" alt="Screen Shot 2022-03-26 at 18 51 27" src="https://user-images.githubusercontent.com/25715018/160238174-f93f1d2f-c6f2-4451-ad99-3f2bf8003fc3.png"> |
| Info hovered | <img width="511" alt="Screen Shot 2022-03-26 at 18 54 35" src="https://user-images.githubusercontent.com/25715018/160238195-abff574c-adfe-4d67-aad2-e3e1318f4da0.png"> | <img width="507" alt="Screen Shot 2022-03-26 at 18 54 44" src="https://user-images.githubusercontent.com/25715018/160238208-3165fd93-4dd4-4800-abec-576cacaa2b7e.png"> |

## Implementation plan

Use the [bootstrap v3.3.7 stylesheet](https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.css) for styling references.

### Props interface

| Prop | Type | Required | Default | Note |
| --- | --- | --- | --- | --- |
| `variant` | `'primary' \| 'danger' \| 'link'` |  | `'primary'` | |
| `size` | `'large' \| 'medium' \| 'small'` |  | `'medium'` | |
| `type` | `'submit' \| 'button'` | | `'button'` | |
| `disabled` | `boolean` | | | Use `aria-disabled` under the hood ([ref](https://css-tricks.com/making-disabled-buttons-more-inclusive/#aa-the-difference-between-disabled-and-aria-disabled)) |
| `loading` | `boolean` | | | |
| `loadingText` | `string` | | | Required if `loading` is `true` |
| `block` | `boolean` | | | |
| `onClick` | `React.MouseEventHandler` | | | |
| `href` | `string` | | | Render an `a` instead of a `button` element if this prop is defined |

### Spacing and typography

The current values of font size, line height, and padding from Bootstrap seem a bit strange to me, as there are some odd numbers in there, which I think would add some challenges in scaling/positioning. Now that we switch to Tailwind, my proposal is to adopt its system and slightly adjust the styling of our component.

| Size | Current | New |
| --- | --- | --- |
| Small | `padding:  5px 10px` <br> `font-size: 16px`<br> `line-height: 1.5` | `padding:  4px 10px` <br> `font-size: 16px`<br> `line-height: 1.5` |
| Medium | `padding:  6px 12px` <br> `font-size: 18px`<br> `line-height: 1.42857143` | `padding:  6px 12px` <br> `font-size: 18px`<br> `line-height: 1.42857143` |
| Large | `padding:  10px 16px` <br> `font-size: 23px`<br> `line-height: 1.3333333` | `padding:  10px 16px` <br> `font-size: 24px`<br> `line-height: 1.3333333` |

References:
- [Tailwind padding values](https://tailwindcss.com/docs/padding) 
- [Tailwind font size and line height customization](https://tailwindcss.com/docs/font-size#providing-a-default-line-height)

### What's not included

| Component | Screenshot | Why
| --- | --- | --- |
| Call to action button | <img width="551" alt="Screen Shot 2022-03-06 at 17 33 33" src="https://user-images.githubusercontent.com/25715018/156919411-9351e672-46f7-438c-bdf7-5ba05a405096.png"> | Should be a standalone component, since its styling is dissimilar to the normal button |
| Dropdown button | <img width="263" alt="Screen Shot 2022-03-06 at 17 45 50" src="https://user-images.githubusercontent.com/25715018/156919745-4d5c3ef6-2a9d-4b01-bd79-6a7c4322b94a.png"> | Should be a standalone component with the support for menu items built in |

## Rough delivery plan

(TBU)
- [x] Remove the stub Button component with a new, basic one (variants and sizes) - #45421
- [x] Support `ref` - #45480
- [x] Add support for `info` variant - #45541
- [x] Add support for hover state - #45541
- [ ] Support various button states and theming - #45665
  - [ ] Ensure active and focus states are covered
- [ ] Support inline and block usages - #45665
- [ ] Support link usage - #45671
  - [ ] Ensure that we render a `button` instead of an `a` if `disabled` is `true`
- [ ] Build [ButtonGroup](https://getbootstrap.com/docs/3.3/components/#btn-groups) (probably a low priority since there isn't a use case for it yet)

**Comment by ahmadabdolsaheb** [comment]
Thanks for taking on the button component and for listing our buttons and their states. 

In the past we styled the buttons' active, hover, and focus states to override Boostrap's styles. 

It might be a good idea to include the active and focus states in the styles as well and replace them with more representative styles on the next iteration.

Note: we also have a less obvious button that we use the in modal `'btn-link'` 

default:
<img width="173" alt="Screen Shot 2022-03-07 at 11 30 48 AM" src="https://user-images.githubusercontent.com/4591597/156995387-b91a6304-2c37-424a-b47d-57f6f4818adb.png">

Hover
<img width="164" alt="Screen Shot 2022-03-07 at 11 32 05 AM" src="https://user-images.githubusercontent.com/4591597/156995598-d4577535-f3d9-414e-ae63-9c2a7ba6d9be.png">

**Comment by huyenltnguyen** [comment]
Thanks @ahmadabdolsaheb! 

I have updated the original post. My plan is to have a dedicated PR just for the button states, since there are a lot to cover.

I have added `link` to the variant list that we need to support. This just reminded me that the accessibility aspect will be very interesting, since there are some differences in the behaviors of button and link. For example, if the component is used as a link and is disabled, we will need to render a `button` tag instead of an `a`, since semantically links cannot be disabled 😄

**Comment by ahmadabdolsaheb** [comment]
The reason that is called link button is that it looks like an active element, but does not steal attention from the donation buttons.

After the bootstrap migration is complete, and the custom component migration is complete, we could audit our library. 
Perhaps we could rename it as tertiary or secondary and style it accordingly.

**Comment by ahmadabdolsaheb** [comment]
Just a heads up that we have a `btn-info` in the codebase. The color needs a little work but we can change that later. You could view it in the settings page of the /settings page or in production next week :)

<img width="643" alt="Screen Shot 2022-03-15 at 4 04 22 PM" src="https://user-images.githubusercontent.com/4591597/158383733-efd00d66-5fa8-4e6e-b59b-6cb4f308e878.png">

**Comment by ahmadabdolsaheb** [comment]
Also other than the styles, what are the challenges of having the CTA be in the same component with the rest of the buttons?

**Comment by ahmadabdolsaheb** [comment]
There are some custom styles that utilizes bootstrap styles such as`.btn`.
We should either include them in the component for now, or re-adjust the custom styles when we move the buttons to production.

**Comment by huyenltnguyen** [comment]
> Also other than the styles, what are the challenges of having the CTA be in the same component with the rest of the buttons?

Yeah it's mostly the styles. we don't seem to have a CTA button in dark theme, and the button is currently a link (`<a>`). I think it would be easier to maintain and develop if we have the component as a separate one, rather than as a variant.

> There are some custom styles that utilizes bootstrap styles such as.btn.
> We should either include them in the component for now, or re-adjust the custom styles when we move the buttons to production.

Agreed. The custom styles have eaten a lot of my time, as I have to decide whether I should copy-paste the styles or try to map the them to what Tailwind has 😅 I've been opting for the latter, it takes a bit more time but will help reduce code that we have to clean up later.

**Comment by huyenltnguyen** [comment]
As noted in https://github.com/freeCodeCamp/freeCodeCamp/pull/45671#issuecomment-1107880378, we will have a Link component that supports the link variant mentioned in the original post.
