### ISSUE TITLE
New Editor layout Improvements ☂️

### ISSUE THREAD

**Issue by ahmaxed** [freeCodeCamp/freeCodeCamp#46178]
### Describe the Issue

This is an umbrella issue to discuss the improvement to the editor layout:
Here is the mockup for your reference.
https://www.figma.com/file/BINkSLYG2VzT9GGEajhoiH/Untitled?node-id=0%3A1
<img width="1190" alt="Screen Shot 2022-06-09 at 4 33 26 PM" src="https://user-images.githubusercontent.com/4591597/173049440-fe831d1e-bbb6-43d1-a13e-2c9a8cf53b86.png">

### General:
- [x] Make the reset step contextual (show it along with the help button at the button of the lower jaw after a few attempts) #46272
- [x] Add `Sign up to save progress` button above all elements in the lower jaw for un-auth #46401
- [x] Add the modal progress bar to the button of the lower jaw. #50167
- [x] Add a share button below the progress bar at the project completion. (Custom twitter cards) #49395
- [x] Confetti at the end of each project.
- [x] Add a quote to the lower jaw when tests pass. #50798
- [ ] Disable button and show loading bar on challenge submission
- [ ] Debounce the challenge submission from the epic not the component

### Mobile:
- [ ] Remove editor side by side display #46276
- [ ] Remove double scroll in the editor tab 
- [x] Reduce the area to the left of the line count to save space. #46309
- [x] Remove `Ctrl + Enter ` on CTA #46239

### Project:
- [ ] Minimize tests when they are not run.

### Needs further discussion:
- Is having multiple stacking options feasible? 
- Making tests challenge completion state more visible when editable region is not visible.
- For mobile, is the lower jaw redundant or the lower buttons row.
- What is the best way to nest tabs and simplify the navigation for Mobile.

### Issues 
- Toggling the editor tab clears the lower jaw state.
- The focus should be on the editable region of the editor when starting a challenge.

ref:
#45997
#46059

**Comment by raisedadead** [comment]
See this milestone for cross ref https://github.com/freeCodeCamp/freeCodeCamp/milestone/27

**Comment by ahmadabdolsaheb** [comment]
@bbsmooth changing the contents of the `test-feedback` for the screen-reader when the tests are run is restricting the duration of the animation. 

I was wondering if it would be possible to aria hide the `test-feedback` and have an sr-only alternative to display the required info to screen readers. 

That way we could lock the desired sr behavior in a test easier.

**Comment by bbsmooth** [comment]
@ahmadabdolsaheb The test result/hint content must be available to screen reader users on the page so that they can go through it manually if needed, so we can't just announce it using an sr-only alternative and hide the actual content from the user. The way it is working now is that we have turned the `#test-feedback` into an aria live region and the screen reader will automatically announce any changes that happen in that div. But I don't see why we couldn't separate the live region out into its own hidden sr-only div live region and then put the results/hint in there as well each time the check is done. Basically we would be duplicating the results/hints in both the current `#test-results` and and the hidden live region. Then screen reader users will still automatically hear the results/hint and will also be able to manually navigate through them if needed. This would remove the aria live region status from `#test-feedback` which I'm assuming is the main cause of your troubles.

**Comment by ahmadabdolsaheb** [comment]
Thank you for your detailed explanation. I am looking into ways to make the lower jaw behave more consistent without duplication. I will pick you up on your offer if I cannot find a plausible way.

**Comment by Ismailtlem** [comment]
Hi,

For the changes we want to do on the editor, are there any wireframes we should respect when implementing the additional things ?

**Comment by Ismailtlem** [comment]
Hi @ahmadabdolsaheb ,

I am interested in going for this one first :  Add the modal progress bar to the button of the lower jaw.
I will start on that asap

**Comment by ahmadabdolsaheb** [comment]
@bbsmooth I am evaluating different lower jaw variations to see if we could save space and give feedback to users more concisely.  Are there any a11y drawbacks with the middle and left design. (the icon could have a test related label)
 
<img width="1892" alt="Screen Shot 2022-06-03 at 4 40 02 PM" src="https://user-images.githubusercontent.com/4591597/173369534-6f8eb625-b6e7-4794-9031-459f3c4ff810.png">


Additionally, since submission and going to the next step is emphasized in the button, could we remove that feedback from the test status? I understand that this div is `aria-live="assertive"`

<img width="567" alt="Screen Shot 2022-06-13 at 4 59 56 PM" src="https://user-images.githubusercontent.com/4591597/173370652-94838a15-6056-4c85-9894-d9993f23a4e5.png">

**Comment by ocBruno** [comment]
Hey I wanted to take on the confetti at the end of each project and was wondering if I can use this package or we want something CSS only or in vanilla js?

https://www.npmjs.com/package/canvas-confetti
https://www.kirilv.com/canvas-confetti/

**Comment by bbsmooth** [comment]
@ahmadabdolsaheb Concerning the feedback for incorrect code, I think either the middle or right one would be fine. The middle one has the text "Code does not pass" so we would not want an aria label on the icon, we would want to hide the icon completely from SR users. The right one does not have that text so we would need to add an aria label or sr-only text that tells the user their code did not pass.

**Comment by ahmadabdolsaheb** [comment]
@bbsmooth thanks for the feedback. Since we will be bringing the success quote from the success modal to the lower jaw, would it be better to keep the congratulations notice or part of it sr-only. Here are some alternatives.

<img width="1269" alt="Screen Shot 2022-06-16 at 3 59 52 PM" src="https://user-images.githubusercontent.com/4591597/174082443-727e3ff7-040a-44fc-91a7-69b591061798.png">

**Comment by bbsmooth** [comment]
I think this might be more of a UI/UX issue than an accessibility issue. I suppose you could make an argument that only using a check mark icon to signal success might be confusing/inaccessible to some people. But since our users will learn what it means relatively quickly (since they are doing this over and over again) I don't think this is a showstopper. I think it might be more of a question of whether you want to congratulate them or if you are satisfied with just the check mark.

**Comment by ojeytonwilliams** [comment]
@RandellDawson suggested this to me in a private message: can we increase the width of the instructions and lower jaw on larger screens?  We could also consider preventing wrapping of inline code if the width is sufficient.

**Comment by ShaunSHamilton** [comment]
```css
.description-container {
  overflow: auto;
  resize: both;
  max-width: unset;
}
```
?

**Comment by ojeytonwilliams** [comment]
Yep, but it's been adjusted relatively recently, so I was curious as to why we're limiting it.

**Comment by ahmadabdolsaheb** [comment]
@moT01 Yes there are a few items that need to go in. @ojeytonwilliams, so the sweet spot for readability is between 45 to 80 characters per line(if I am not mistaken). 

Also in the current design our check button spread through block. If we extend the width of the instructions, it would look less like a button.  That being said, I would be happy to make change to improve the readability and

**Comment by yrhemendra** [comment]
Hello Sir, Can you assign this issue to me? I have a good sense of visual presentation.

**Comment by ieahleen** [comment]
@yrhemendra 
We typically do not assign issues. Instead, we accept the first pull request that comprehensively solves the issue.

Issues labelled with `help wanted` or `first timers only` are open for contributions.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/). We prioritize contributors following the instructions in our guide. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing - our community will be happy to assist you.

**Comment by BalanaguYashwanth** [comment]
I saw there no one is building share button, so i am looking into it, how to "Add share button below the progress bar at the end of each project. (Custom twitter cards)"

Let me know any restrictions are there

**Comment by ojeytonwilliams** [comment]
Thanks for taking a look @BalanaguYashwanth. @ahmadabdolsaheb do we have specific requirements for the share button?

**Comment by BalanaguYashwanth** [comment]
Hello guys,

I am facing difficulty to extract the data from **meta.json file** of respective **superBlock** under **curriculum** folder.  

**solution which i know -**

I can use fetch method by passing dynamic superBlocks into curriculum file path to get json data.

Is there is any solution ?

**Comment by BalanaguYashwanth** [comment]
Atlast raised PR - https://github.com/freeCodeCamp/freeCodeCamp/pull/49395

After lot of learnings. If not reviewed, review it by running in local. Definitely worth your time.

**Comment by ahmadabdolsaheb** [comment]
@BalanaguYashwanth, thank you for your interest. 
You could get all the challenge related data (block, superblock, certificate, ) from the   challengeMetaSelector.

Here are the user stories:
1) Button should be an icon button with a twitter icon.
2) The icon should be a font-awesome icon (with the current setup) or a react svg icon component similar to other icons in the repo.
3) Button should be placed with the other icon buttons in the lower jaw.
4) Button should create a twitter card.
) Twitter card should include percentage progress, block name, freecodecamp hashtag, and a link to the related block in the superblock map.
5) Twitter card text be using i18n functionality to facilitate translations. 

@ojeytonwilliams, just wanted to double check the user stories with you before proceeding. 
Note: the percentage completion will be added to Redux in https://github.com/freeCodeCamp/freeCodeCamp/pull/49381 , so Ideally you should wait until that pr is in to finalize the twitter card's text.

**Comment by BalanaguYashwanth** [comment]
If you see below image👇 most of the **buttons are too large**, if i keep twitter icon without text inside these large buttons, then I don't think so it will suitable (according to user stories)

<img width="1509" alt="image" src="https://user-images.githubusercontent.com/36238382/219425597-cad0e371-ccfe-4310-8c73-b0783a1e283a.png">


------------

But Few courses some icons are small but in my latest PR, i made these buttons also large

<img width="872" alt="image" src="https://user-images.githubusercontent.com/36238382/219425976-db354ac9-0d59-402f-b829-b36796fd8aac.png">

If you see my implementation might be looks good (refer below image), If you still not satisfied then send me some figma designs will proceed with it for changing buttons.


<img width="872" alt="image" src="https://user-images.githubusercontent.com/36238382/219427552-700f72a2-1b12-44e8-abd6-2f847b911e2a.png">

<img width="872" alt="image" src="https://user-images.githubusercontent.com/36238382/219427616-198e3700-cf98-4f51-91e0-136a588e9b2c.png">

---------------
CC: @ojeytonwilliams

**Comment by bbsmooth** [comment]
A question. What if the user needed to click on the "Copy link to share" button more than once? Is there a reason we shouldn't allow the user to do this? 

I'm concerned that the name of the button changes to "Copied successfully" after they click on it. This seems to prevent the user from using the original functionality of the button more than once (I'm assuming we would disable the button if we changed the name). 

If there is no reason to prevent the user from clicking the button more than once then I would suggest we leave the button name as "Copy link to share" and display the success message some other way, such as the flash alert, or even adding a success message directly above or below the button.

**Comment by Sboonny** [comment]
the function isn't disabled, when the button is clicked, but to answer you we shouldn't disable it at all, I hate it when I copy something and can't copy it again, I referesh the page

**Comment by BalanaguYashwanth** [comment]
Hey @Sboonny @bbsmooth,

Thanks for showing interest😅, You can actually click the button more than once there won't be any restrictions, 

Also, I tried looking other ways of "Copied successfully" message, Atlast what i was implemented looks perfect interms of UI/UX. 

Because any user if they click on "Copy link to share" button after seeing "Copied successfully" message, they will understand they copied it.

But still if you think there is a better way to showing it interms of UI/UX as well. then let me know by updated information by discussing with your team, I will definetly implement it. Moral of the story is twitter button won't looks good on large buttons (as per user stories what it mentioned).

**Comment by bbsmooth** [comment]
> if you think there is a better way to showing it interms of UI/UX as well. then let me know

FCC has a flash alert that other buttons use to notify the user that a button press has been successful. Makes sense to me to use that here. For an example, see any of the Save buttons on the Settings page.

**Comment by BalanaguYashwanth** [comment]
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/36238382/219526605-2ef741cd-9845-4e4a-a32e-26cc3fa24a4c.png">

This one are you saying @bbsmooth

**Comment by BalanaguYashwanth** [comment]
![copy-video](https://user-images.githubusercontent.com/36238382/219528032-3c1eacc6-21ff-40f0-a650-5a1a065dc969.gif)


Can i know feedback on this also 😅 @bbsmooth

**Comment by BalanaguYashwanth** [comment]
I need some designs so that i can code it

**Comment by Nirajn2311** [comment]
> ![copy-video](https://user-images.githubusercontent.com/36238382/219528032-3c1eacc6-21ff-40f0-a650-5a1a065dc969.gif) [ ![copy-video](https://user-images.githubusercontent.com/36238382/219528032-3c1eacc6-21ff-40f0-a650-5a1a065dc969.gif) ](https://user-images.githubusercontent.com/36238382/219528032-3c1eacc6-21ff-40f0-a650-5a1a065dc969.gif) [ ](https://user-images.githubusercontent.com/36238382/219528032-3c1eacc6-21ff-40f0-a650-5a1a065dc969.gif)
> 
> Can i know feedback on this also 😅 @bbsmooth

The main issue I see with this is that if it's too fast then the user might miss the "Copied successfully" message and if too slow then they'll have to wait for some time before clicking the button again. Instead it would be better to show the "Copied successfully" message in the flash alert.

**Comment by BalanaguYashwanth** [comment]
ok @Nirajn2311 thanks for resolving my doubt and will change quickly, I hope below flash alert will be fine for implementation.

![image](https://user-images.githubusercontent.com/36238382/219949720-1e7ef65a-2852-4d8f-a401-f13690c3e54d.png)

**Comment by Nirajn2311** [comment]
Yes, that's the flash alert I was talking about.

**Comment by BalanaguYashwanth** [comment]
ok

**Comment by ahmadabdolsaheb** [comment]
Here is the mock, 
<img width="954" alt="Screen Shot 2023-02-20 at 3 24 39 PM" src="https://user-images.githubusercontent.com/4591597/220106776-4862a192-dc95-4087-8fe4-3988b6a465ad.png">

**Comment by BalanaguYashwanth** [comment]
Only 1st courses have small button, remaining courses have long buttons like below👇

<img width="550" alt="image" src="https://user-images.githubusercontent.com/36238382/220147359-9ae73753-2376-4c47-917c-470aaa827835.png">

**Comment by BalanaguYashwanth** [comment]
Updated share button feedback with flash alert

![freecodecamp-copied](https://user-images.githubusercontent.com/36238382/220508405-2a68e6a9-d434-4e61-8188-0e37d5b861b0.gif)


CC: @Nirajn2311 @bbsmooth

**Comment by ahmadabdolsaheb** [comment]
@BalanaguYashwanth, yes the new editor refers to the editor of the first certification.
The button is to be implemented in the new editor layout only.
Please let me know if you need help with navigating the spec.

**Comment by ahmadabdolsaheb** [comment]
Let's measure the user engagement and decide down the line. That being said the majority of users interact with the first certificate (https://www.freecodecamp.org/learn/2022/responsive-web-design/).

**Comment by BalanaguYashwanth** [comment]
ok, Can i implement twitter share button only for first certificate. so that my PR will also gets easily merged and also we can see the user engagement for it.

**Comment by ahmadabdolsaheb** [comment]
@BalanaguYashwanth, yes.  Just be sure to follow the user stories outlined here: https://github.com/freeCodeCamp/freeCodeCamp/issues/46178#issuecomment-1433058616

**Comment by BalanaguYashwanth** [comment]
Yes, just now again i read your comment, Here are some takeaways :-

-  Only First certificate course will suitable for the implementation of small twitter icons, For other certificate courses buttons needs to change from large button to small button. so I need some clarification on it.

**Comment by ahmadabdolsaheb** [comment]
There is only going to be one variation of this button since it will be implemented in the first certificate next to other icon buttons.

**Comment by BalanaguYashwanth** [comment]
thanks

**Comment by BalanaguYashwanth** [comment]
Please checkout whenever you are free, and also update me where i can improve


https://user-images.githubusercontent.com/36238382/222530026-15d56b34-d7c9-41c6-b730-287905324ab8.mp4

CC: @ahmadabdolsaheb

**Comment by ahmadabdolsaheb** [comment]
Thank you uploading the video.
Here are a couple of points:
1) the whole text should say "I have completed 100% of Learn HTML by Building a Cat Photo App project #freeCodeCamp".
2) the link should go to https://www.freecodecamp.org/learn/2022/responsive-web-design/#learn-html-by-building-a-cat-photo-app

**Comment by JordanMooree** [comment]
Question regarding the `Disable button and show loading bar on challenge submission` task. So we want a disabled `Check Your Code` button **after** click then re-enables after returning a success/failed submission response (i.e. congrats or try again message)?

The reason I ask is that it seems that the responses from the submission are fast enough not to need a disabled button after the submission but wondering if this feature is needed in case a user's internet is slower.

**Comment by a2937** [comment]
Hello. Does the FreeCodeCamp platform already have a confetti animation in the CSS?

**Comment by ahmaxed** [comment]
No, but a it used to have a JS version in the past. Feel free to re-work it into your pr.
https://github.com/freeCodeCamp/freeCodeCamp/pull/45393

**Comment by shootermv** [comment]
can i try `confetti at the end of project` task?

**Comment by ahmaxed** [comment]
I am closing this issue as most of the actionable items have been addressed. We could open individual issues for the remaining items if necessary.
