### ISSUE TITLE
Setup Linting and Tests

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#48444]
The new API needs help setting up linting & testing:

- [x] Setup ESLint, Prettier, typescript-eslint
- [x] Setup CI workflows
- [x] Setup Jest-based tests

Related: https://github.com/freeCodeCamp/freeCodeCamp/pull/48437
