### ISSUE TITLE
Ability to personalize the profile page

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#49631]
# One of the things missing from freeCodeCamp, but it can do:

- Learners can put whatever data they want into their profile.
- They can customize their profiles to their heart's content.
- It should be something they might want to show off.

---

# Ideas need more discussion

## ability to customize the site

- [ ] Expose the `id` attributes that they're allowed to hook into.
- [ ] The profile page should make it more obvious that they can edit it. #49133
- [ ] Allow user to post their skills, whether for a language we don't teach in the curriculum like C. Maybe something that isn't related to programming, like being fluent in multiple language.
- [ ] A sandbox where they can add a (limited) amount of text to play with. Then we could inject some CSS into that.
- [ ] Ability to choose between evolving avatars.

## Use external resources 

- [ ] Link the [Forum](https://forum.freecodecamp.org/) account with its achievement to the Profile page.
- [ ] Allow campers to embed their GitHub readme in their Profile.
- [ ] Potentially we could allow people to add new libraries from the libraries we are hosting, or prolific contributors added to a list of allowed libraries.
- [ ] Allow people to post their open source contributions.
- [ ] Use prebuild component from libraries like [material](https://m3.material.io/components), after adding the needed parts for accessibility. An option is for layout is [SmolCSS](https://smolcss.dev/).

## inspiration from other sites

- [ ] Allow users to be creative with their background images, like how stream is doing it. 
- [ ] LinkedIn have assignment to get badge. We can do the same with our certifications by giving badges for people who pass certain certification or finish a take home project.

## New features linked to profile

-  Community section where: 
- [ ]  Learners can upvote other people profile, downvote them, or report them.
- [ ]  Learners can follow each other.
- [ ]  Learners can share their earned certification.

## Flexibility

- [ ] ability to revert to basic style in the setting page, if customization went wrong.
- [ ] ability to share pieces of their profile for the community, for other people to use.
- [ ] ability to vote for libraries that impact the profile section.

---

# Issues that are open for contribution

- [ ] although ability to customize profile is desired, a generic good-looking design isn't a bad idea https://github.com/freeCodeCamp/freeCodeCamp/issues/48234
- [ ] user should be able to add portfolio, but their input isn't valid and sometime weird, this issue aims to put spotlight into it https://github.com/freeCodeCamp/freeCodeCamp/issues/49132

**Comment by abdnafees** [comment]
@Sboonny From where shall someone begin working on this issue for their first fCC PR?

**Comment by Sboonny** [comment]
by discussing how the feature should be implement

**Comment by abdnafees** [comment]
Alright, I will explore the code base over the weekend.

**Comment by abdnafees** [comment]
@Sboonny Could you guide me as to where to find the User menu component? Is this the file `client/src/components/profile/profile.tsx`?

**Comment by Sboonny** [comment]
can you be more specific? I don't know what you mean by User menu

**Comment by abdnafees** [comment]
Yeah, sorry I stated it incorrectly. I am talking about the `profile.tsx` file.

**Comment by Sboonny** [comment]
no worries, yes the profile is where the issue is centered

**Comment by abdnafees** [comment]
I went through the requirements mentioned above and my first impression while going through the code base was that this would be a big ticket. As a novice open-source contributor, I don't know where to start.

Also, my first idea is to add a dropdown on the top of the profile page as shown in the screenshot below.

<img width="1392" alt="Screenshot 2023-03-13 at 18 32 18" src="https://user-images.githubusercontent.com/19777158/224717290-027f25a8-3435-4175-a5c5-3b797bf25814.png">

**Comment by Sboonny** [comment]
> I went through the requirements mentioned above and my first impression while going through the code base was that this would be a big ticket. As a novice open-source contributor, I don't know where to start.

Ya, even a prolific contributor won't be able to handle this single-handedly, and your discussion has pointed details that I haven't pointed out in the issue, which is a good contribution.

**Comment by abdnafees** [comment]
Here is what I came up with after taking some inspiration from GitHub's README.md feature. One of the things I am not sure about is whether we can diverge from the single-column center layout of the existing page.

The first one shows how it will look in Markdown.
![image](https://user-images.githubusercontent.com/19777158/224816754-bb9cd55f-3278-422d-8dec-9399669ad6d9.png)


This one is the final preview of the Markdown text.
![image](https://user-images.githubusercontent.com/19777158/224816921-d22002a7-5528-47f0-a05e-0d5fb08eb94d.png)


Looking forward to feedback and discussion.

**Comment by Sboonny** [comment]
This aligns with portfolio redesign 🤔 👍.

> One of the things I am not sure about is whether we can diverge from the single-column center layout of the existing page.

I can see how the page styling is getting in the way of the campers, because of the centering of the context, yes it should go when campers add their own styling, or go indefinitely.

**Comment by abdnafees** [comment]
What should go? Should the campers go where they are at the moment or can we move them around?

**Comment by abdnafees** [comment]
Yeah makes sense. This will require additional components as I read that fCC is moving away from `react-bootstrap`.

**Comment by ahmadabdolsaheb** [comment]
It might be worthwhile to review github/kaggle/linkedin profile page to see to see how to organize user input types (certifications, projects, experience, technologies, etc)

**Comment by ahmadabdolsaheb** [comment]
Here is the updated requirements list for the upcoming profile page.

Profile Sections:
1. Profile image 
2. Profile image border
3. Username
4. Name
5. Date started
6. location
7. Stats: current streak, points, and longest streak
8. certification
9. badges
10. Socials: Twitter + GitHub + personal website + forum
11. Activity map 
12. Timeline 
13. Card System with predefined sections(languages, skills, hobbies, open source contributions)

Features:
- CSS customizability: allow users to inject styles in a filed and see the results with the option to save.
- Expose ids
- Ability to reset styles
- Add edit icon on the profile sections #49133 
- Expose the `id` attributes that they're allowed to hook into.

Not feasible for NVP:
- Learners can follow each other. (requires infra adjustment)
- Ability to vote for libraries that impact the profile section.
- Ability to share pieces of their profile for the community, for other people to use. 
- Use prebuilt component from libraries like [material](https://m3.material.io/components), after adding the needed parts for accessibility. An option is for layout is [SmolCSS](https://smolcss.dev/).
- LinkedIn have assignment to get badge. We can do the same with our certifications by giving badges for people who pass certain certification or finish a take home project.
- ability to revert to basic style in the setting page, if customization went wrong. (remove additional css from customization box)
- Allow campers to embed their GitHub readme in their Profile. (archives the same with card system)

Questions
- should images be removed for the portfolio items?
- should users be able to change the order of section? (11-13)
- should timeline and activity map be merged since they display the same info?
- should the display of sections be toggle-able?

Once the questions are answered, we could move on to creating user stories and related issues.

**Comment by Pratik1603** [comment]
Please assign this to me

**Comment by Sboonny** [comment]
This is the context that I was focusing on for Post MVP:

We should be careful of how much we allow the campers to change, because these profiles are host on freeCodeCamp site, and if they change too much, and it no longer accessible, we should have a switch that make their profile private, until they make the necessary changes to make it accessible.

- Add the ability to determined how accessible the edited profile is.
- Add the ability to make it private, if it isn't up to standards.
- Add the ability to block the camper from turning their website public, without updating the issues in it. 
- notify the camper, that their profile has been made private, and should be updated until it is.

**Comment by Sembauke** [comment]
We d=
