### ISSUE TITLE
Cleanup props on User Schema and DB records for a User

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#50344]

**Comment by ShaunSHamilton** [comment]
**Fields to Remove**

- [ ] `github`
  - Not set anymore, and not used on server/client
- [x] `isGithub`
- [x] `isLinkedIn`
- [x] `isTwitter`
- [x] `isWebsite`
- [x] `password`
- [ ] `timezone`
  - Not currently used. Do we plan to?
- [ ] `verificationToken`
  - Appears to be entirely related to LB
  - Not set this anywhere except to `null` in `User.confirm` which is never directly called
- [ ] `badges`
  - Not currently used. Do we plan to?
- [ ] `rand`
  - Do we need this?

**Transformation Strategy**

We have concluded an initial (needed) normalization will involve transforming optional array types into `[]`.

`completedChallenges.files` is an array type, but does not exist on every completed challenge. Do we want to add `files: []` to every single `completedChallenges` element? If not, we will not be able to make use of strong typing using Prisma.

- `completedChallenges`
  - remove all `__<>` properties
- `profileUI`
  - remove all `__<>` properties
- `progressTimestamps`
  - `[{ timestamp: Double }]` -> `[Double]`
  - `[Null]` -> `[]`
  - `[Int64]` -> `[Double]`
- `partiallyCompletedChallenges`
  - `Undefined` -> `[]`
  - `[[]]` -> `[]`
  - Does this have any actual values? What is this used for?
- `yearsTopContributor`
  - `Undefined` -> `[]`
  - `[String]` -> `[Double]`
    - A string of length 4 takes 24 bytes, a double takes 8 bytes
- `savedChallenges`
  - `Undefined` -> `[]`
- `badges`
  - `Undefined` -> `[]`
  - Remove?

**Comment by raisedadead** [comment]
The `is*` flag seems to be present in the code, last I checked. Does it have any impact?

**Comment by ShaunSHamilton** [comment]
> Do you think removing has any impact?

Thank you for making me double-check. The `is<>` fields are never used, but are still being set:

https://github.com/freeCodeCamp/freeCodeCamp/blob/b24c939322430cdee2daa51e258e2f8991353241/api-server/src/common/models/user.js#L808-L827

At one point, I assume they were used for logic on the client like:

```javascript
if (isGithub) {
  return <h1>{user.githubProfile}</h1>
}
```

Now, we just use:
https://github.com/freeCodeCamp/freeCodeCamp/blob/b24c939322430cdee2daa51e258e2f8991353241/client/src/components/profile/components/social-icons.tsx#L90

**Comment by ShaunSHamilton** [comment]
> Did you get a chance to profile the memory and CPU usage?

Yes, but only from a whole-system perspective - I did not see an easy way to log MongoDB-specific usage other than `htop`.

| Process | CPU [%] | Memory [GB] |
| -------- | ------ | ------- |
| `mongod` | 20 < x < 30 | 18 < x < 23 * |
| script | 60 < x < 70 | 6 < x < 8 |

* 4GB of swap was used, but I do not know who ate this

**Comment by ShaunSHamilton** [comment]
> Do you have the specs for the machine you run this on? How many CPUS, total memory?

Yes, but I do not think it is remotely comparable. As discussed, we should go with a staging test. Then, the only thing we need to decide is what machine runs the script.

**Comment by naomi-lgbt** [comment]
> Then, the only thing we need to decide is what machine runs the script.

I'd suggest spinning up a DigitalOcean droplet to run the script and destroying it once done.

**Comment by ShaunSHamilton** [comment]
The [normalization script](https://github.com/freeCodeCamp/scripts/pull/205) is ready (for review at least).

**Action Plan**

- [ ] Merge normalization script
- [ ] Generate hammer script to 🔨 the API
  - Typical Camper behaviour causing reads/writes to DB
  - Match typical concurrents
  - [ ] Merge
- [ ] Seed staging with production
  - Upgrade to match prod
- [ ] Deploy normalization script to droplet 💧 
- [ ] Deploy hammer script possibly to same 💧 
- [ ] Run and observe

**Comment by moT01** [comment]
Is this post-mvp?

**Comment by ojeytonwilliams** [comment]
It doesn't seem strictly necessary, so post-MVP seems best.

**Comment by ojeytonwilliams** [comment]
@ShaunSHamilton based on our recent discussions, I think we're likely to do this after deploying the new api. As such, I'm moving it to Post-MVP. Please move it back if I've misunderstood.

**Comment by ShaunSHamilton** [comment]
To prevent LB from adding back stuff we do not want, this should be Post MVP. Thanks, @ojeytonwilliams
