### ISSUE TITLE
Quotes in Code Strings

### ISSUE THREAD

**Issue by naomi-lgbt** [freeCodeCamp/freeCodeCamp#51036]
Way back when we first established our internationalisation flow and standards, one of the points we landed on was that string literals should be wrapped in code tags to prevent translation, but should **not** be wrapped in quotes.

I vaguely remember that there was some sound justification for this decision, but have long since lost track of where that conversation was or the reasoning behind it.

However, we are starting to see an increase in confusion from not being explicit with quotes around our string literals - one very frequent example is the Record Collection challenge, where campers are confused by the difference of the `"tracks"` string assigned to the `prop` parameter and the `tracks` property of the record object.

I think it is time that we re-evaluate this standard, and consider allowing quotes where necessary to facilitate camper comprehension and prevent unnecessary cognitive overhead.

---

JavaScript Algorithms and Data Structures (Beta)
- [x] Learn Basic JavaScript by Building a Role Playing Game https://github.com/freeCodeCamp/freeCodeCamp/pull/53523
- [x] Learn Form Validation by Building a Calorie Counter #53762 
- [x] Learn Basic String and Array Methods by Building a Music Player #53954
- [x] Learn the Date Object by Building a Date Formatter #53948
- [x] Build a Palindrome Checker Project #53940
- [x] Learn Modern JavaScript Methods by Building Football Team Cards #53955
- [x] Learn localStorage by Building a Todo App #54008
- [ ] Learn Recursion by Building a Decimal to Binary Converter
- [x] Build a Roman Numeral Converter Project #53915
- [ ] Learn Basic Algorithmic Thinking by Building a Number Sorter
- [ ] Learn Advanced Array Methods by Building a Statistics Calculator
- [ ] Learn Functional Programming by Building a Spreadsheet
- [ ] Learn Regular Expressions by Building a Spam Filter, Not started
- [x] Build a Telephone Number Validator Project #53922
- [ ] Learn Basic OOP by Building a Shopping Cart
- [ ] Learn Intermediate OOP by Building a Platformer Game
- [ ] Learn Intermediate Algorithmic Thinking by Building a Dice Game
- [x] Build a Cash Register Project #53924
- [ ] Learn Fetch and Promises by Building an fCC Authors Page
- [ ] Learn Asynchronous Programming by Building an fCC Forum Leaderboard
- [x] Build a Pokémon Search App Project #53939 

Scientific Computing with Python (Beta)
- [x] Learn String Manipulation by Building a Cipher #53418 
- [x] Learn How to Work with Numbers and Strings by Implementing the Luhn Algorithm #53516 
- [x] Learn Lambda Functions by Building an Expense Tracker #53520
- [x] Learn Python List Comprehension by Building a Case Converter Program #53521 
- [ ] Learn Regular Expressions by Building a Password Generator #53456 
- [ ] Learn Algorithm Design by Building a Shortest Path Algorithm #53428
- [x] Learn Recursion by Solving the Tower of Hanoi Puzzle #53569
- [ ] Learn Data Structures by Building the Merge Sort Algorithm
- [ ] Learn Classes and Objects by Building a Sudoku Solver
- [ ] Learn Tree Traversal by Building a Binary Search Tree

Scientific Computing with Python Projects ~~(Wait for #53146)~~ 
- [x] Arithmetic Formatter #53956
- [x] Time Calculator #53957
- [ ] Budget App
- [ ] Polygon Area Calculator
- [ ] Probability Calculator.

**Comment by jeremylt** [comment]
The Record Collection one is definitely one that consistently generates confusion. Perhaps when we are talking about string literals and variable names in the same block of text in JS, that's when we should use quotation marks.

**Comment by ieahleen** [comment]
This is still an issue, and tripping up campers often. Should we consider giving this a go?

**Comment by ilenia-magoni** [comment]
I have an argument for the presence of quotes: there are many cases for strings that have a space at beginning of ends, using quotes it make this space more visible, and it avoid the space disappearance when importing to crowdin.
Example for step 23 of RPG [English](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a23d1c5f1c93161f3582ae.md) vs [Arabic](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/arabic/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a23d1c5f1c93161f3582ae.md)
where there is `Monster Name: ` in the first but `Monter Name:` in the second. With quotes it should solve the issue.

**Comment by jeremylt** [comment]
Yeah, I am seeing similar confusion about string literals in code blocks vs variable names in the new curriculum

**Comment by Dario-DC** [comment]
I agree with adding quotes. It should solve the issue with the trailing space and help campers, too.

**Comment by ShaunSHamilton** [comment]
I like quotes, as long as we are settled on using double-quotes `"`, unless there is a really good reason not to (escape sequences and all that).

**Comment by Dario-DC** [comment]
The new Python curriculum uses only single quotes. Would it be a problem to use single quotes there and double quotes in the other courses?

**Comment by ilenia-magoni** [comment]
I have made a list of the projects in the javaScript and Python beta courses, so we can keep track of which ones have already been updated

**Comment by RGHANILOO** [comment]
Hey Folks,
I am going to start working through the chores/list of the unchecked boxes,  my question is when it comes to raising a PR, do i need to raise an issue first relating to the specific chore so there is a ticket assigned to it?
Just observing the  previous PRs that are merged, each one appears to have a unique ticket that is being closed by the merge or so i think.
Guidance would be appreciated 
Thanks

**Comment by raisedadead** [comment]
Left a comment for your similar discord query: https://discord.com/channels/692816967895220344/715074489422970962/1212444023348924476

**Comment by RGHANILOO** [comment]
Build a Palindrome Checker Project was merged on : #53940

record on the issue doesn't seem to have been updated

**Comment by ilenia-magoni** [comment]
yeah, someone has to update it manually

**Comment by Ksound22** [comment]
Should the strings in the `querySelector` methods below be surrounded in quotes too?

```js0
document.querySelector(".start-screen")
document.querySelector(".checkpoint-screen")
```

**Comment by naomi-lgbt** [comment]
They should already be surrounded, yes.

**Comment by ilenia-magoni** [comment]
Considering https://github.com/freeCodeCamp/freeCodeCamp/issues/54558
we probably need to evaluate better the criteria on when to use quotes, I'm still of the idea to use them, but maybe not everywhere

**Comment by ShaunSHamilton** [comment]
I must admit, I had not considered this with HTML. At the end of the day, I suspect the best course of action involves:
1) Consistency in the way we represent things in the content
2) Clarification at the beginning what representation means what

**Comment by Ksound22** [comment]
Does it matter if the quotes are single or double quotes? Is there any of them particularly recommended?

**Comment by ilenia-magoni** [comment]
The stylistic choice is to prefer double quotes for the JavaScript certifications and single quotes fir the Python certifications @Ksound22

**Comment by a2937** [comment]
I'm having a lot of trouble finding something wrong with the Sudoku Solver string literals.
