### ISSUE TITLE
Decouple packages for faster build and DX

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#51416]
```[tasklist]
### TODO (later this year)
- [ ] Create and move the `api-server` repo.
- [ ] Create and move docs to Contribute repo.
- [ ] Create and move UI components to the UI repo.
- [ ] Create and move client-scripts (SASS, etc.) and distribute them as a package.
```

**Comment by naomi-lgbt** [comment]
Woah tasklists are new and really cool to look at.

On a related note, I'd be happy to spearhead the Contribute repo.

**Comment by raisedadead** [comment]
Yes - they are the perfect replacement for ☔ issues. Thanks for your offer I have created a thread we can take it up there.

**Comment by ahmaxed** [comment]
Since the UI components is being finalized. I would prefer moving the UI components after we have migrated away from bootstrap. This should all still happen this year.

**Comment by raisedadead** [comment]
Don't panic, I mentioned "later this year".

**Comment by Sembauke** [comment]
Hey I am closing this as stale outdated. Please, if you think we should keep it open please feel free to do so.

Make sure to update it.
