### ISSUE TITLE
Migrate Button component off of Bootstrap

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#52092]
## Context

We are swapping out the Bootstrap's `Button` component for the `ui-components` one. The PR for this change is already created (#51443), but we would like to split the PR into smaller parts to ease the review process and to minimize the risk of introducing regression. 

I'm opening this issue to track the PR series as well as to document issues I find during the work. The issue can be closed once all of the PRs are merged.

## Goals

- Completely remove the usage of Bootstrap `Button`
- Ensure that the replacement doesn't introduce bugs
- Opportunistically remove the existing CSS overrides in /learn 
- Adding CSS overrides may be unavoidable, but try to minimize them as the component library should already cover most of the use cases. The overrides should be accompanied with a code comment explaining the temporary state of the code.

## High level approach

My plan is to split the change per page or section. Though since `Button` is also used in shared components, it's possible that we will have PRs that impact several pages/components. I'll see how my strategy works out as I dive in 😄 

### ui-components

- [x] #52115
- [x] Export the Button component for consumption (#52204)

### Learn

- [x] `client/src/client-only-routes/show-certification.tsx` (#52204)
- [x] `client/src/client-only-routes/show-unsubscribed.tsx` (#52326)
- [x] `client/src/client-only-routes/show-user.tsx` (#52326)
- [x] `client/src/components/Donation/card-update-alert-handler.tsx` (#52816)
- [x] #52349 
  - [x] `client/src/components/Donation/donate-completion.tsx`
  - [x] `client/src/components/Donation/donate-form.tsx`
  - [x] `client/src/components/Donation/donation-modal.tsx`
  - [x] `client/src/components/Donation/stripe-card-form.tsx`
- [x] `client/src/components/Header/components/login.tsx` (#52525)
- [x] `components/helpers/form`
  - [x] `client/src/components/helpers/form/block-save-button.tsx` (#52525)
  - [x] Delete `client/src/components/helpers/toggle-button.css` (#52525)
- [x] `client/src/components/profile/components/time-line.tsx` (#52378)
- [x] `components/settings` (#52525)
  - [x] `client/src/components/settings/about.tsx`
  - [x] `client/src/components/settings/certification.tsx`
  - [x] `client/src/components/settings/danger-zone.tsx`
  - [x] `client/src/components/settings/delete-modal.tsx`
  - [x] `client/src/components/settings/email.tsx`
  - [x] `client/src/components/settings/honesty.test.tsx`
  - [x] `client/src/components/settings/honesty.tsx`
  - [x] `client/src/components/settings/internet.tsx`
  - [x] `client/src/components/settings/portfolio.tsx`
  - [x] `client/src/components/settings/privacy.tsx`
  - [x] `client/src/components/settings/reset-modal.tsx`
  - [x] `client/src/components/settings/toggle-button-setting.tsx`
  - [x] `client/src/components/settings/toggle-radio-setting.tsx`
  - [x] `client/src/components/settings/user-token.tsx` (#52340)
  - [x] `client/src/components/settings/username.tsx`
- [x] `client/src/pages/update-email.tsx` - this has to be done together with the settings page as there are CSS collision caused by the settings page's overrides (#52525)
- [x] `client/src/pages/email-sign-up.tsx` (#52378)
- [x] Modals and widgets (#52378):
  - [x] `client/src/components/signout-modal/index.tsx`
  - [x] `client/src/components/staging-warning-modal/index.tsx`
  - [x] `client/src/components/solution-display-widget/index.tsx`
  - [x] `client/src/components/SolutionViewer/exam-results-modal.tsx`
  - [x] `client/src/components/SolutionViewer/project-modal.tsx`
- [x] `templates/Challenges`
  - [x] `client/src/templates/Challenges/classic/lower-jaw.tsx` (#52577)
  - [x] `client/src/templates/Challenges/codeally/show.tsx` (#52577)
  - [x] `client/src/templates/Challenges/components/completion-modal.tsx` (#52577)
  - [x] `client/src/templates/Challenges/components/help-modal.tsx` (#52577)
  - [x] `client/src/templates/Challenges/components/project-preview-modal.tsx` (#52577)
  - [x] `client/src/templates/Challenges/components/reset-modal.tsx` (#52577)
  - [x] `client/src/templates/Challenges/components/shortcuts-modal.tsx` (#52577)
  - [x] `client/src/templates/Challenges/components/tool-panel.tsx` (#52577)
  - [x] `client/src/templates/Challenges/dialogue/show.tsx` (#52577)
  - [x] `client/src/templates/Challenges/exam/components/exam-results.tsx` (#52577)
  - [x] `client/src/templates/Challenges/exam/components/exit-exam-modal.tsx` (#52577)
  - [x] `client/src/templates/Challenges/exam/components/finish-exam-modal.tsx` (#52577)
  - [x] `client/src/templates/Challenges/exam/components/foundational-c-sharp-survey.tsx` (#52577)
  - [x] `client/src/templates/Challenges/exam/components/foundational-c-sharp-survey-alert.tsx` (#52339)
  - [x] `client/src/templates/Challenges/exam/show.tsx` (#52577)
  - [x] `client/src/templates/Challenges/fill-in-the-blank/show.tsx` (#52577)
  - [x] `client/src/templates/Challenges/ms-trophy/link-ms-user.tsx` (#52577)
  - [x] `client/src/templates/Challenges/ms-trophy/show.tsx` (#52577)
  - [x] `client/src/templates/Challenges/odin/show.tsx` (#52577)
  - [x] `client/src/templates/Challenges/projects/tool-panel.tsx` (#52577)
  - [x] `client/src/templates/Challenges/video/show.tsx` (#52577)
- [x] `templates/Introduction`
  - [x] `client/src/templates/Introduction/components/cert-challenge.tsx` (#52577)

**Comment by Sboonny** [comment]
Hey @huyenltnguyen, which buttons that you haven't started yet, that I can take over?

**Comment by ojeytonwilliams** [comment]
Thanks for reopening this, @huyenltnguyen.

So, the issue was that passing `href` as a prop meant that `onClick` was ignored by the Button (and it became impossible to claim certifications).

I'm looking into improving our test coverage. It needs to be crystal clear that something serious has gone wrong if this button stops working. That's not currently the case. Also, hopefully, TypeScript can help us here: it should be complaining if someone passes an incompatible set of props. I'll see what I can do!

**Comment by ojeytonwilliams** [comment]
I'm a little unsure what the desired behaviour is. `onClick` and `disabled` should be allowed on both types of buttons? Then the logic is: if `download`, `href` or `target` are passed to the Button, then show the Link component.

Is that correct?

**Comment by ojeytonwilliams** [comment]
> Hi @ojeytonwilliams, I sincerely apologize for the mess. I'll help look into the issue as well.

Thanks, I've not been following the UI Components development that closely, so I'll definitely need it. And don't worry about the bug - as a general rule, disabling tests for functionality that you're not deliberately removing is a bad idea, but that should have been caught in QA.

> > onClick and disabled should be allowed on both types of buttons? 
> Yes, both of them are acceptable on both button types.

Great, thanks for confirming. That should make the types a little easier to manage.

> We only look for the truthiness of the href value. If the value is truthy, we render an <a>; otherwise, we render a <button>

Hmm. I'm pretty sure that `download` and `target` don't make sense for `button` elements, so we should probably switch to using `a` elements if any of them are truthy.
