### ISSUE TITLE
Navbar is inconsistent across the platforms

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#52119]
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/1884376/eee24bf4-b047-46b7-a12f-e81e0b93bcd5)

```[tasklist]
### Tasks
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/53656
- [ ] The nav on the forum has the loading bar with an incorrect z-index
- [x] On forum, the theme chooser is not available anymore
```

**Comment by raisedadead** [comment]
@ahmaxed can you please investigate? 

One quick note about the forum is that they (Discourse) changed the layouts and deprecated the older layouts. In their defense they did give us a warning months ago. Not sure if it is related.

**Comment by raisedadead** [comment]
Another quick note is I do like the nav on learn which has a decent breathing room than the other platforms.

**Comment by raisedadead** [comment]
Fixed the theme chooser:

<img width="536" alt="image" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/1884376/6dce471f-1ce2-4745-a9ef-3cd78248805e">

**Comment by ahmaxed** [comment]
@raisedadead, I am not sure what you are referring regarding "The nav on the forum has the loading bar with an incorrect z-index" could you share a screenshot?

**Comment by raisedadead** [comment]
![forum-nav z-index](https://github.com/freeCodeCamp/freeCodeCamp/assets/1884376/354e5497-0893-4e27-b857-11d0894f6ebc)

**Comment by Universe-stack** [comment]
Hi @raisedadead, I'd like to help fix this issue. Thanks

**Comment by QuincyLarson** [comment]
@ahmaxed Sorry to resurrect this issue, Ahmad, but I just saw the updated navbar on /learn and /news and I feel like it looked better (and took up less vertical real estate) before. Is there a way we can make the navbar skinnier everywhere rather than making it fatter everywhere? I felt the original dimensions we've used for the past 6 or 7 years looked fine.

**Comment by ahmaxed** [comment]
https://github.com/freeCodeCamp/forum-theme/pull/114/ takes care of the loader on the forum.
