### ISSUE TITLE
Playwright doesn't test mobile

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#52198]
### Describe the Issue

While reviewing playwright PR's, I kept getting failures locally, but everything was passing in the CI. After a little digging with Oliver, we found that the [mobile chrome and mobile safari tests are running locally](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/e2e/playwright.config.ts#L67) (if they're not turned off), but [not in CI.](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/.github/workflows/e2e-playwright.yml#L80) Seems like we should probably add one or both of those mobile browsers to CI. Note that many tests will likely fail and need updating if we do. Perhaps we didn't add those for a reason, not sure.

### Expected behavior

To have mobile tests

### First Steps

While we discuss enabling the mobile tests in our CI, PRs would be welcomed to resolve the following failures in mobile testing:

```[tasklist]
### Failing Spec Files
- [x] `action-row.spec.ts` - #52446
- [x] `desktop-layout-component.spec.ts` - #52439, #52934
- [x] `editor-tabs.spec.ts` - #52454
- [x] `editor.spec.ts` - #52518
- [ ] `hotkeys.spec.ts`
- [x] `landing.spec.ts` - #52474
- [x] `lower-jaw.spec.ts`
- [x] `notes.spec.ts` - #52475
- [x] `preview.spec.ts` - #52519
- [x] `progress-bar.spec.ts` - #52520
- [x] `reset-modal.spec.ts`
- [x] `shortcuts-modal.spec.ts` - #52480
- [x] `tool-panel.spec.ts` - #52479
```

**Comment by rahulsuresh-git** [comment]
@moT01 I'd like to take a look at this issue.

**Comment by ojeytonwilliams** [comment]
We're not running them in CI yet.
