### ISSUE TITLE
Launch new JS curriculum

### ISSUE THREAD

**Issue by naomi-lgbt** [freeCodeCamp/freeCodeCamp#52295]
Evergreen tasklist to prepare for and launch.

```[tasklist]
### Tasks
- [x] Complete the rest of the practice projects
- [x] Complete the certification projects - use new IDs for these to avoid conflict with the old ones
- [x] Audit order of blocks in meta.json files AND remove the logic that skips new JS when testing order
- [x] Audit the intros - every project should have an intro in the similar format as the RWD projects (have Quincy approve the copy?)
- [ ] Deploy new JS curriclum as BETA on **english only** learn
- [ ] Collect and apply feedback
- [ ] Mark previous certification as legacy, deploy new certification at top of learn map
- [ ] As translations are complete, mark as audited - until then, old JS will stay at the top of the i18n blocks
```

Will be adding tasks as needed.

**Comment by moT01** [comment]
> Complete the certification projects - use new IDs for these to avoid conflict with the old ones

We used the same ID's when we did the new RWD cert projects - cause the actual certification didn't change - same five projects, just done in the multifile editor. If we use new Id's, we will need a new cert. e.g. We can't take away anyone's cert, so everyone will need to complete those five projects (again if they're the same) to get the new one - not sure if the projects are the same or different. Perhaps that's what we want - not sure.

**Comment by jdwilkin4** [comment]
@moT01 

> not sure if the projects are the same or different. Perhaps that's what we want - not sure.

4 of the 5 projects are similar to what is currently live on the site. The main difference is that instead of just writing out an algorithm, campers will also build out a basic UI. 

For example, here is the updated [palindrome checker](https://palindrome-checker.freecodecamp.rocks/)

Instead of the caesars cipher project, there will be a pokemon search app
https://pokemon-search-app.freecodecamp.rocks/

**Comment by naomi-lgbt** [comment]
>  If we use new Id's, we will need a new cert. e.g. We can't take away anyone's cert, so everyone will need to complete those five projects (again if they're the same) to get the new one

That is the plan, yes. The existing cert will become a legacy cert, and the new project-based one will be a separate cert.
