### ISSUE TITLE
Welcome to Hacktoberfest 2024

### ISSUE THREAD

**Issue by naomi-lgbt** [freeCodeCamp/freeCodeCamp#56170]
# What is Hacktoberfest?

[Hacktoberfest](https://hacktoberfest.com) is a month-long celebration of open source. Projects, such as freeCodeCamp, can opt-in to participate. When they have done so, contributors (just like you!) can make pull requests to the project that are eligible for the event.

Contributors who have made four eligible pull requests (PRs which receive an "approve" review or are merged into the default branch) can earn a digital badge through Holopin - this is customisable and evolves over time.

> [!NOTE]
> Contributors who have a PR merged for this issue may also reach out to Naomi on Discord to claim a special Hacktoberfest 2024 role.

# How to Participate

We are in the process of overhauling our interactive curriculum. This change will include new lesson formats such as videos, lectures, interactive labs and workshops, and more.

Part of this initiative requires creating knowledge comprehension quizzes. We are asking contributors to participate in Hacktoberfest by making pull requests to create the content for these quizzes.

We need pull requests for each of the following quizzes.

<details>
<summary><h2>Show List</h2></summary>

```[tasklist]
### Tasks
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56174
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56175
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56176
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56177
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56178
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56179
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56180
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56181
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56182
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56183
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56184
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56185
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56186
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56187
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56188
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56189
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56190
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56191
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56192
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56193
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56194
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56195
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56196
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56197
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56198
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56199
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56200
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56201
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56202
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56203
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56204
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56205
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56206
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56207
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56208
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56209
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56210
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56211
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56212
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56213
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56214
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56215
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56216
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56217
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56218
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56219
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56220
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56221
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56222
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56223
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56224
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56225
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56226
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56227
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56228
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56229
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56230
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56231
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56232
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56233
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56234
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56235
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56236
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56237
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/issues/56238
```

</details>

> [!IMPORTANT]
> To allow as many contributors to participate as possible, we kindly ask that:
> - Each pull request create exactly one (1) quiz
> - Each contributor create no more than one pull request for this issue

# How to Write a Quiz

All quizzes can be found in the new [`front-end-development`](https://github.com/freeCodeCamp/freeCodeCamp/tree/main/curriculum/challenges/english/25-front-end-development) directory.

A quiz is contained in a single markdown file, such as [the Design Fundamentals quiz](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/25-front-end-development/quiz-design-fundamentals/66ed901ff45ce3ece4053eba.md).

These markdown files use a template:

````md
---
id: id-goes-here
title: Semantic HTML Quiz
challengeType: 8
dashedName: semantic-html-quiz
---

# --description--

Answer all of the questions below correctly to pass the quiz.

# --quizzes--

## --quiz--

### --question--

#### --text--

Placeholder question

#### --distractors--

Placeholder distractor 1

---

Placeholder distractor 2

---

Placeholder distractor 3

#### --answer--

Placeholder answer
````

Quizzes are all multiple choice. The "distractors" are incorrect answers to the question. You may list the distractors in any order. The `--answer--` should be the answer which is correct.

A quiz should have a total of 20 questions related to the topic. We will attempt to provide a list of sub-topics to choose from before the event starts.

# Examples

Here is an example of what a completed quiz file should look like: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/25-front-end-development/quiz-basic-html/66df3b712c41c499e9d31e5b.md

Here is an example of a pull request which follows our contributing guidelines might look like: https://github.com/freeCodeCamp/freeCodeCamp/pull/56417

# Plagiarism and AI-generated Content

Do **NOT** copy questions directly from other sources, even if paraphrased. Questions you submit should be your own creations. This includes using generative AI to create questions - please do NOT use AI (ChatGPT, Claude, etc) to create questions.

# Interested in Contributing?

> [!TIP]
> Before contributing, be sure to read our [documentation](https://contribute.freecodecamp.org) thoroughly. If you have any questions, reach out to us in [Discord](https://discord.gg/KVUmVXA) and we will be more than happy to assist you.

If you are interested in contributing, please respond OH THE ISSUE YOU'D LIKE TO WORK ON. We will then add you to the issue so other contributors know you have claimed that quiz.

> [!CAUTION]
> If you have claimed a quiz, and we have seen no activity within 7 days, we will release the quiz so another contributor may claim it.

We look forward to seeing your contributions. Happy Coding! 💜

**Comment by naomi-lgbt** [comment]
Thank you for your interest in contributing. This issue will be unlocked and opened for contribution when Hacktoberfest starts on October 1st.

> [!CAUTION]
> Pull requests which are **created before** October 1st will not be eligible for Hacktoberfest. We appreciate enthusiasm, but encourage you to hold off on contributing to this issue until the event has begun.

If you wish to be notified when this issue is opened for contribution, subscribe to notifications:

![image](https://github.com/user-attachments/assets/a1f1f2f5-8c64-403a-a5be-5d5495d8f886)

**Comment by naomi-lgbt** [comment]
## When you create a pull request

The template asks for an issue number that your PR closes. **PLEASE** do not use this top-level `56170` issue. **INSTEAD**, you should use the number for the specific quiz issue you are assigned.

**Comment by naomi-lgbt** [comment]
# This issue is now open

If you would like to work on this issue, please leave a comment so we can assign it to you.

[Be sure to read our contributing guidelines](https://contribute.freecodecamp.org).

**Comment by jdwilkin4** [comment]
Closing this issue since all of the corresponding issues have been closed. 👍
