### ISSUE TITLE
New Curriculum:  Regular Expressions + 2 Checkpoints

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/FreeCodeCamp#5794]
We're pretty anemic in our coverage of regular expressions and we need to add more waypoints.

We should have a whole new section that is just Regex.  Target 15-20 Waypoints + 2 Checkpoints

This issue to discuss and track development of new Waypoints.

Some Brainstorms from Curriculum Development:
* Wildcard (`.`) - 1 WP
* Quantity Specifiers (`+`, `*`, and `{x,y}`) - 3 WP
   * Optionality (non Greedy Capture `?`) - 1 WP
* Character Classes `[abc]` and their Inverse - 2-3 WP
   * Character Ranges `[a-z]` and `[0-9]` - 2 WP
* Case Insensitivity Flag (`i`)
* Global Flag (`g`)
* Pre-defined character classes and their inverse (`\d`/`\D`/`w`/`\W`/`\s`/`\S`)  - 3 WP?
* Checking for Patterns (back reference) - 1 WP
* Capture Groups - 2 WP (Replace?)
* Anchors (`^` and `$`) - 2 WP

For Reference:
http://www.regular-expressions.info/tutorial.html

Waypoint Definitions:
- [ ] Using `.test`
- [ ] Literal Matches 1 - `abc`
- [ ] Literal Matches 2 - `ab|cd`
- [ ] Flags - `i` - Case Insensitive
- [ ] Flags - `g`- Global
- [ ] Wildcard - `.`
- [ ] Character Class 1 - `[abc]` - Count Vowels?
- [ ] Character Class 2 - `[abc]` ??
- [ ] Character Class 3 - `[a-z0-9]`
- [ ] Character Class 4 - `[^abc]`
- [ ] Quantity Specifiers 1 - `+`
- [ ] Quantity Specifiers 2 - `*`
- [ ] Checkpoint 1 - Match simple literal patterns with optional followers (character class)
- [ ] Anchors 1 - `^`
- [ ] Anchors 2 - `$`
- [ ] Pre-Defined Character Class 1 - `\w`
- [ ] Pre-Defined Character Class 2 - `\W`
- [ ] Pre-Defined Character Class 1 - `\d`
- [ ] Pre-Defined Character Class 1 - `\D`
- [ ] Pre-Defined Character Class 1 - `\s`
- [ ] Pre-Defined Character Class 1 - `\S`
- [ ] Quantity Specifiers 3 - `{x,y}`
- [ ] Quantity Specifiers 4 - `{x,}`
- [ ] Quantity Specifiers 5 - `{,y}`
- [ ] Optionality - `?`
- [ ] Capture Groups - `( )`
- [ ] Capture groups 2 - Using Replace?
- [ ] Checkpoint 2 - ??

## How to Contribute
* Comment on this Issue with:
   * Ideas about how to do the above curriculum
   * Write out sample descriptions or sample code
   * Claim a waypoint to work on
   * Discuss in the [CurriculumDevelopment Room](https://gitter.im/FreeCodeCamp/CurriculumDevelopment)
* Edit or create a Waypoint
   * Write PRs against [this branch](https://github.com/FreeCodeCamp/FreeCodeCamp/tree/feature/regular-expression-curriculum)

**Comment by CaroleAnneHannon** [comment]
What about a-z ? (and/or A-z A-Z)
for when trying to match characters but not the whole \w?

**Comment by SaintPeter** [comment]
@CaroleAnneHannon Brilliant!  Added to the list.

**Comment by patsul12** [comment]
For the capture groups, maybe have a waypoint where you have to count the number of vowels in a string using regex. [aeiou]

**Comment by CaroleAnneHannon** [comment]
Also the basic literals
cat
actually is for the word cat and is different from [cat]

And the OR (cat|dog)
for when people want to OR whole literals and not just single characters? (since for single characters [] is just easier)

Quantity specifiers should also have ? for 0 or 1

**Comment by CaroleAnneHannon** [comment]
The current regexp waypoints all use the String.match

What about using the regexp itself for [.test](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test)?

**Comment by SaintPeter** [comment]
Good ideas @CaroleAnneHannon!

**Comment by HoBi** [comment]
Maybe also add 

- *lazy quantifier* `*?`. (https://regex101.com/r/uV1yH1/1 - try to remove `?` to see the difference)
- *match everything enclosed* `(?:foo)` - the same as `(foo)`, but does not create a capture group
- *positive lookahead* `foo(?=bar)` - capture foo if is follower by bar - https://regex101.com/r/uV1yH1/2
- *negative lookahead* `foo(?!bar)` - capture foo it is not follower by bar - https://regex101.com/r/uV1yH1/3

I also recommend https://regex101.com/#javascript for testing.

**Comment by SaintPeter** [comment]
@HoBi Those are some good ideas.
It would be nice if we could come up with a lazy quantifier (also called Optionality, I'm told) that kinda made sense - IE: that we want to capture a particular word or section of a word to change a sentence . . . but having it be non-lazy means the sentence has an opposite meaning.  Essentially, we must try to be clever.

I like using the regex101 save facility for doing the development work.

---

I'm also thinking it might be interesting to write new courseware to support this.  Something like this site:
http://regexone.com/

I don't think it would be too hard to write, would just need to define what it would look like.

**Comment by arecvlohe** [comment]
Sample problems:
1. URL match
2. Email match
3. Hex value match
4. HTML tag match
5. Valid/Invalid password
6. Valid/Invalid username
7. Valid/Invalid ticket number
8. Count the number of valid/invalid items
8. Password maker
10. Camel case maker 
11. Parse logs for error code

**Comment by pradeepce** [comment]
Word boundaries `\b` can be a waypoint, accompanied by how they are a zero-length match.

**Comment by BerkeleyTrue** [comment]
Work on this has moved to https://github.com/FreeCodeCamp/CurriculumExpansion

Happy Coding
