### ISSUE TITLE
Curriculum Request: Create challenges to teach security and debugging

### ISSUE THREAD

**Issue by Greenheart** [FreeCodeCamp/FreeCodeCamp#6669]
**Curriculum Request: Create challenges to teach security and debugging.**

Pre-face:
> I've written about this **suggested improvement** [in a recent Medium post](https://medium.com/@ greenheart/this-article-gave-me-an-idea-e0711e21c4ce#. 2zgmfx7lk) and describe both the issue, solution and reasoning behind it over there.

> **I would love to collaborate with other contributors to create these challenges, so feel free to come with suggestions!** :smile:

> ~ @greenheart

---

### Ideology :
- Cover important security topics through challenges.
- Challenges should have user stories to be completed, for assessing the user progress.
- Award a security-focused certification ?

### List of resources to check and create the curriculum :
- [Interactive tutorial on XSS](https://xss-game.appspot.com/) 6 Good challenges might be good enough to just add to the curriculum in the same way like for example the Node.js challenges?
- [Google HTML5 Security (2014)](https://www.youtube.com/playlist?list=PLOU2XLYxmsIIkEU3Z_xdVo9EADurbdxKa)
- [XSS - Google App Security](https://www.google.com/about/appsecurity/learning/xss/index.html)
- [CSRF - JSRecipes](http://sahatyalkabov.com/jsrecipes/#!/backend/csrf-protection-with-express)
- [Node/Express Security Overview](https://www.youtube.com/watch?v=W-8XeQ-D1RI)
- [HTTPS and user auth with node](https://youtu.be/Y4nQzmI_Nj0?t=35m42s)
- [Helmet.js - HTTP Header secutiry for node/express](https://github.com/helmetjs/helmet)
- [Nodesecurity.io - Talks, Blogs and Whitepapers](https://nodesecurity.io/resources)
- [XSS - [DrapsTV, YouTube]](https://www.youtube.com/watch?v=M_nIIcKTxGk&list=PL1A2CSdiySGIRec2pvDMkYNi3iRO89Zot#t=6.019541)

#### Idea 1 (Based on current Backend challenge Format)
- Campers are given a starter (template|bootstrap) repository.
- The repository can be a simple `todo list` app or any basic CRUD app.
- They are given challenges with incremental difficulties, to fix vulnerabilities.
- Different types of vulnerabilities can be split across challenges, with their own set of user stories.

##### Part 1
- Fork [OWASP NodeGoat](https://www.owasp.org/index.php/OWASP_Node_js_Goat_Project) : **This is a great resource and looks quite promising.**
- Write beginner-friendly instructions (if the tutorial provided is too advanced)
- Split into several smaller challenges
- An example of a challenges could be: Patch the code for Server Side JS Injection (changing eval to JSON.parse), ensure that all dependencies are secure (run [nsp](https://github.com/nodesecurity/nsp)), [fix de-/misconfigured header](https://securityheaders.io/).

##### Part 2
- This [XSS-game from Google](https://xss-game.appspot.com/) is a great way to get practical experience with this specific threat.
- 6 levels of increasing difficulty
- Tested by @Greenheart - "Great challenges that are ready to be used as is **if we get permission from Google**"

### Road map :
- [ ] **Learn about vulnerabilities, summarize most important facts that we can make use of.**
- [ ] **Decide what type of challenges should be developed, this will be**
  - [ ] API or CRUD?
  - [ ] Only back-end, or should we involve client-side security in this project too?
    _(Maybe just focus on back-end first?)_
- [ ] **Decide which security-topics we want to cover**
  - [ ] using `.env` for sensitive variables like `port, mongo uri, api keys` etc. @Rafase282
  - [ ] Escape dangerous characters in requests to the server --> The server should not store html in the db to stop users from adding custom script-tags to posts that could be viewed by other users and possibly run malicious code in their browsers. (Protect against some XSS-attacks)
  - [ ] Protect from cross site request forgery (CSRF) by adding invisible "_csrf"-token to forms and inputs. ([Example implementation using Express](http://sahatyalkabov.com/jsrecipes/#!/backend/csrf-protection-with-express))
- [ ] **Implement the challenges with features that showcases these security-topics**
  - [ ] Insecure app-version to use as template / starter kit
  - [ ] Secure version to use for reference/code review
- [ ] **Video Challenges related to Security.**
  - [ ] Supplement challenges with videos related to security.
  - [ ] Might even be a part of the security challenges / certification?

**This an initial suggestion for a workflow, but please give feedback!**

**Comment by Greenheart** [comment]
## The plan
- [ ] Create a draft with different alternatives
- [ ] Present to Rex
- [ ] Present to whole core team

**Comment by QuincyLarson** [comment]
This is quite a collection of challenges!

The more of these challenges we could create for FCC's editor (as opposed to having to clone an existing repo and set up a local dev environment) the better. That said, if it's impossible to mimmic, say, XSS on Free Code Camp, then we can cover that specific topic with a NodeSchool-like package (OWASP NodeGoat looks great!)

**Comment by BerkeleyTrue** [comment]
Work continues here https://github.com/FreeCodeCamp/CurriculumExpansion

Happy Coding
