### ISSUE TITLE
Move email login to passwordless 

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#8165]
The first part of simplifying our authentication issues is to move to passwordless login. 

~~For this we should use some sort of emailed-out token, such as this library:
https://github.com/florianheinemann/passwordless~~

This involves: 
- [x] re-add email verification
- [x] create user email sign up logic
- [x] change email login to use temp tokens sent via email to login
- [x] removing password reset logic
- [x] restrict API access to the user creation

DevOps
- [ ] Remove all passwords from database (@berkeleyTrue)

Edit(@berkeleyTrue):
Removed passwordless module. This is well within the abilities of the loopback framework

**Comment by ttymed** [comment]
What's the word on this?  Is this still an issue?

**Comment by raisedadead** [comment]
@ttymed yup its very much in progress, Checkout the open PR's for the details.

**Comment by muteb1** [comment]
I can help with the login details

**Comment by QuincyLarson** [comment]
Closing in favor of continuing the discussion here: https://github.com/FreeCodeCamp/FreeCodeCamp/issues/10407

**Comment by BerkeleyTrue** [comment]
#10407 Does not cover this issue.

**Comment by bottled-ant** [comment]
I don't know how to help, but I can't fint a way to register or login...
tryed to login with github -> ups, something went wrong
tryed to register with email -> email already exists
tryed to reset password -> ups, something went wrong
counting 3 days now that I try to register or login, for noobies like me this is highly upsetting and a turn away.
I only have basic knowledge in HTML CSS php MySQL and was looking to use this platform to expand my skills and knowledge.

**Comment by raisedadead** [comment]
Hi @bottled-ant Welcome to FreeCodeCamp, and sorry to hear that.

if you are having issues with the main website at https://FreeCodeCamp.com please log a fresh issue with the details at https://github.com/FreeCodeCamp/FreeCodeCamp/issues/new

We will try our best and sort your issue.

This thread is about our new authentication mechanism, that will be launched soon.

Thanks for reporting, and happy coding!

**Comment by bottled-ant** [comment]
sorry form misplacing my comment i will start a new problem

**Comment by systimotic** [comment]
@QuincyLarson Now that passwordless has been implemented in the beta, can this be closed?

**Comment by raisedadead** [comment]
@systimotic thanks, yes we can close this in favor of https://github.com/freeCodeCamp/freeCodeCamp/issues/14559, which is the only remaining task on this list.
