### ISSUE TITLE
Applied Visual Design Challenges

### ISSUE THREAD

**Issue by atjonathan** [FreeCodeCamp/FreeCodeCamp#9413]
For the new curriculum update, we need to create the following new challenges under a new section called **Applied Visual Design**:

- [ ] Create visual balance using the text-align property
- [ ]  Align Text Left
- [ ]  Align Text Right
- [ ]  Center Text
- [ ]  Justify Text
- [ ]  Adjust the Width of an Element Using the Width Property
- [ ]  Adjust the Height of an Element Using the Height Property
- [ ]  Create a Visual Balance width and height property of an element (element initially exists out of balance among other elements).
- [ ]  Adjust the Width of one Element Relative to Another Element
- [ ]  Adjust the Height of one Element Relative to Another Element
- [ ]  Create visual emphasis by using bold text
- [ ]  Create visual emphasis by using underline text
- [ ]  Create visual emphasis by using the italic property on text
- [ ]  Create visual emphasis by using the strikethrough property
- [ ]  Create visual emphasis by adjusting the background-color property of text and property of the foreground.
- [ ]  Create visual emphasis by adjusting the size of a header versus a paragraph tag.
- [ ]  Create visual emphasis by making an card like element stand out by adding a box-shadow.
- [ ]  Create a Graphic Using CSS
- [ ]  Learn how CSS Keyframes Work
- [ ]  Create movement using CSS Animation
- [ ]  Learn how Bezier Curves work
- [ ]  Use a Bezier Curve to Move a Graphic
- [ ]  Make Motion more Natural using a Bezier Curve
- [ ]  Use CSS Animation to Change the Hover State of a Button
- [ ]  Add a Box Shadow to an Element
- [ ]  Use CSS animation to Raise a Card Element with a Box Shadow on Hover
- [ ]  Increase the Opacity of an Element
- [ ]  Change the Position of an Element on its Z Axis
- [ ]  Use the box-shadow z-axis and Opacity together to Animate an Element
- [ ]  Reuse a block of CSS class names to recreate an element over and over again with proper spacing in order to create pattern
- [ ]  Use a CSS linear gradient to Create a Striped Element
- [ ]  Create a gradual CSS Linear Gradient
- [ ]  Use the CSS Transform Property to Scale an Element on Hover
- [ ]  Use the CSS transform Property SkewX
- [ ]  Use the CSS transform Property SkewY
- [ ]  Create Proportionality by Sizing a Header Versus a Paragraph Tag.
- [ ]  Create Rhythm with CSS animate Property
- [ ]  Create Rhythm using the Infinity Property
- [ ]  Use an the Infinity Property to Make a CSS Heart Beat with a Steady Rhythm
- [ ]  Create a Varying Rhythm
- [ ]  Use a Varying Rhythm to Make Stars Twinkle at Different Rates
- [ ]  Observe unity by looking at sites like AprilZero. This is more of an exercise in understanding how all the different principles of design create unity.
- [ ]  Create a Line Using the hr Element
- [ ]  Create a more Complex Shape using CSS and HTML
- [ ]  Create Visual Direction by Fading in an Element to the left.
- [ ]  Use the CSS Transform Scale Property to Change the Size of an Element.
- [ ]  Create Texture by Adding a Subtle Pattern as a Background Image
- [ ]  Learn about Complimentary Colors
- [ ]  Learn about Tertiary Colors
- [ ]  Adjusting the Color of Various Elements to Complimentary Colors
- [ ]  Adjust the Hue of a Color
- [ ]  Adjust the Tone of a Color
- [ ]  Learn the Importance of Ratios in Type
- [ ]  Learn About Modular Type
- [ ]  Apply Different Ratios to Type Using the font-size Property
- [ ]  Create a Typographic Style Guide
- [ ]  Set the value of h1 to 68px
- [ ]  Set the value of h2 to 52px
- [ ]  Set the value of h3 to 40px
- [ ]  Set the value of h4 to 32px
- [ ]  Set the value of h5 to 21px
- [ ]  Set the value of h6 to 14px
- [ ]  Set the value of Paragraph text to 16px
- [ ]  Adjust the Color of an Anchor Tag
- [ ]  Adjust the Hover State of an Anchor Tag
- [ ]  Adjust the font-weight of header 1–5 tags.
- [ ]  Adjust the line-height of a paragraph until the paragraph is properly spaces.
- [ ]  Use the text-transform property to make text uppercase.
- [ ]  Incorporate a Google Fonts Into your Header
- [ ]  Assign a Google Font using CSS

Other propositions for this new section will be added as separate issues and given the **Applied Visual Design Challenges** Milestone.

These are still open to change. If you are interested in working on a specific one of these new challenges, please complete the following steps:

1. Leave a comment on this issue, with the challenge you are looking to work on and I will assign you.
2. Try and have a pull request opened with the new challenge within the next two weeks after you comment.

Feel free to contribute to these, and chat with us in the new [**AppliedVisualDesignChallenges**](https://gitter.im/FreeCodeCamp/AppliedVisualDesignChallenges) chat room.

**Comment by atjonathan** [comment]
Closing in favour of https://github.com/FreeCodeCamp/CurriculumExpansion/issues/7

**Comment by lawgotcode** [comment]
Hello guys, Anybody still post in here?

**Comment by HKuz** [comment]
Hi @lawgotcode - anyone watching this repository will see your posts in here, even though it's a closed issue 😄 - let us know what you're looking to discuss. For this issue specifically, a lot of the challenges listed above were created in the curriculum expansion push and are running on beta.freecodecamp.com and getting QA'd by the community. If you want to propose a new challenge, I'd say to open a new issue with your thoughts 👍 Cheers!
