### ISSUE TITLE
Responsive Design Challenges

### ISSUE THREAD

**Issue by atjonathan** [FreeCodeCamp/FreeCodeCamp#9414]
For the new curriculum update, we need to create the following new challenges under a new section called **Responsive Design**:
- [ ] Create a Media Query
- [ ] Set a Responsive Breakpoint
- [ ] Create a Compound Media Query
- [ ] Make an image responsive
- [ ] Use a retina image
- [ ] Make typography responsive

Other propositions for this new section will be added as separate issues and given the **Responsive Design Challenges** Milestone.

These are still open to change. If you are interested in working on a specific one of these new challenges, please complete the following steps:

1. Leave a comment on this issue, with the challenge you are looking to work on and I will assign you.
2. Try and have a pull request opened with the new challenge within the next two weeks after you comment.

Feel free to contribute to these, and chat with us in the new [**ResponsiveDesignChallenges**](https://gitter.im/FreeCodeCamp/ResponsiveDesignChallenges) chat room.

**Comment by Manish-Giri** [comment]
@atjonathan Just curious, will the current section on [Responsive Design with Bootstrap](https://www.freecodecamp.com/map#nested-collapseResponsiveDesignwithBootstrap) be merged into this new **Responsive Design** section?

**Comment by atjonathan** [comment]
@Manish-Giri, no that section will stay as is. However, we will probably rename it to something like **Front End Frameworks/Bootstrap**. This is an entirely new section.
I don't believe there are any wiki articles on challenge creation. Take a look at the JSON Structure of other challenges, and try to replicate that. https://github.com/FreeCodeCamp/FreeCodeCamp/pull/9286 might be helpful.

**Comment by atjonathan** [comment]
Closing in favour of https://github.com/FreeCodeCamp/CurriculumExpansion/issues/10

**Comment by webdevjeffus** [comment]
In the "Create a Media Query" challenge, the instructions and the test don't match. The instructions say: 

> Add a media query, so that the p tag has a font-size of 10px when the device's height **is smaller than 800px**.

**Smaller than 800px** means 799 or less, so the correct media query _should_ be "max-width: 799px". The test actually passes with "max-width: 800px", which translates into English as **800px or smaller.**

Basically, the instructions call for **width < 800**, but the test checks for **width <= 800**. Either one is fine, but they need to match each other.
