### ISSUE TITLE
GitHub Wiki Migration

### ISSUE THREAD

**Issue by raisedadead** [FreeCodeCamp/FreeCodeCamp#9731]
We are migrating the GitHub Wiki to the Forum and will be removing the Wiki from this repository. 
The wiki repository may stay for archiving.

Before removing the GitHub wiki we should look into the migration of the below:
- [ ] The wiki solutions that are pointed from the map aside.
- [x] The help links that point to wiki (workarounds) from within the challenges **(#10010)**
- [x] Guides such as how to make pull request, translation guides etc. **(#10010)**
- [x] **MOST IMPORTANT**: The help found a bug article that is linked in the button **(#10010)**
- [x]  Audit and move any links that currently point to the wiki in the read me, challenges etc. **(#10010)**

Anything that I might have missed.

**Comment by Rafase282** [comment]
https://github.com/FreeCodeCamp/wiki/issues/1211

**Comment by Rafase282** [comment]
1. The Articles from map have been moved but the Map.md will not be moved as we now have a powerful search functionality and categories.
2. Wiki articles for the challenges all should have the updated internal url, are you talking about from the main site pointing to the wiki?
3. All those guides are there already.
4. The article is there and this is the link http://forum.freecodecamp.com/t/how-to-report-a-bug/19543
5. The readme was not migrated as there is no need for git.

**Comment by P1xt** [comment]
A question came up recently on the forums about how one might update a wiki page for a challenge - which made me wonder: If all the wiki articles are migrated to the forums in their current form, doesn't that remove the feature wherein anyone can push a change to github to improve the wiki content? I would think that on the forums, typically folks will look at the shiny, leader yellow post and consider it an unalterable authority, because it's no longer open source in that it's no longer modifiable by "the masses". Is there a new process coming down the pike for wiki contributions / enhancements?

Also, I'm rather wondering if the wiki migration is the extra load on the forums that's causing the forums to crash.
